### ISSUE TITLE
Duplicate and incrementing is decrementing

### ISSUE THREAD

**Issue by natros** [krasa/StringManipulation#10]
![dup-and-dec](https://cloud.githubusercontent.com/assets/4996289/12221741/75db3e82-b79f-11e5-9b78-7b9a6796b9cd.gif)

Thanks

**Comment by krasa** [comment]
You could just use decrement, since it looks on the +- sign.
Or if there are more values and you do not want inconsistencies, you could temporarily replace - for +, and then back, that's really easy with multiple carets now.
Nothing I can do here.

**Comment by natros** [comment]
I thought it was only taking into account the number, not the signal. The current behavior make sense.
Decrement will not work because it will insert the duplicate before the selection.

I'm closing this since it's not a bug.
Thank you.
