### ISSUE TITLE
Comma-separated string gets converted incorrectly to camel case

### ISSUE THREAD

**Issue by yfrolov** [krasa/StringManipulation#100]
Hello,

I'm not sure if it's a bug, however, when I convert very long CSV string to the camel case, the plugin does only the first element correctly and the rest of them get converted to the Pascal Case.

Input string: `"Submitted By","Owner","Creation Date","Root Cause", ...`

Expected result: `"submittedBy","owner","creationDate","rootCause", ...`
Actual result: `"submittedBy","Owner","CreationDate","RootCause", ...`

Thank you in advance.

**Comment by krasa** [comment]
Thanks for the report. The next release should work fine.

Btw, have you found some better plugin/tool to do it?

**Comment by yfrolov** [comment]
> Thanks for the report. The next release should work fine.
> 
> Btw, have you found some better plugin/tool to do it?

Thanks a lot!
I tried 3-4 other plugins but none of them were able to do it. I ended up writing my on function in Python. :)
