### ISSUE TITLE
Sort subselection based on delimiter

### ISSUE THREAD

**Issue by Joe-Degler** [krasa/StringManipulation#101]
**Is your feature request related to a problem? Please describe.**
Currently, our linter requires that all imports are in alphabetical order. As we use Python, we selectively import multiple things from a single class.
Example:
`from wtforms import BooleanField, Form, HiddenField, IntegerField, PasswordField, RadioField, SelectField, DateField,`

The linter requires DateField to be after BooleanField and before Form.

Unless I'm missing something, the current necessary flow would be:
1. Mark all the commas (using ALT+J)
2. Separate them onto newlines
3. Sort the lines using existing Line-sorting functionality
4. Mark all commas again
5. Remove newlines

**Describe the solution you'd like**
Given the fact that we already have something that can actively split a selected String by delimiters ( Align/Sort by Columns ), I imaged a solution to be similar: You make a selection, a window pops up, lets you quickly select the delimiter (or auto-infer it if it's obvious / configured ), and then sort the subselection. 

**Describe alternatives you've considered**
I thought initially this is what Align/Sort by Columns was for, but it isn't. Perhaps it can be an added functionality in that tab if you only have a single line available ("Sort Header"?)

**Comment by krasa** [comment]
How about that: 
![image](https://user-images.githubusercontent.com/1160875/84599418-306a5080-ae72-11ea-9098-96cd9a687637.png)
