### ISSUE TITLE
Un/Escape selected HTML text feature and &apos; / single quote

### ISSUE THREAD

**Issue by thibaut-decherit** [krasa/StringManipulation#102]
Un/Escape selected HTML text feature does not un/escape `&apos;`/`'`

**Comment by krasa** [comment]
Interesing, `org.apache.commons.text.StringEscapeUtils.escapeHtml4` says:
`Supports all known HTML 4.0 entities, including funky accents. Note that the commonly used apostrophe escape character (&apos;) is not a legal entity and so is not supported).`

but it could be escaped to &#39; - https://stackoverflow.com/questions/2083754/why-shouldnt-apos-be-used-to-escape-single-quotes
