### ISSUE TITLE
Make increment duplicates respect leading zeros

### ISSUE THREAD

**Issue by briankchan** [krasa/StringManipulation#103]
Currently, the increment duplicates feature strips leading zeros after the first entry. E.g., incrementing duplicates on

```
001
001
001
001
```

results in

```
001
2
3
4
```

It would be nice to check for leading zeros on the first number and prepend leading zeros to the incremented numbers to match.

The above example would instead result in

```
001
002
003
004
```

---

Also, 2 related bugs: values with leading zeros currently get parsed as octal, so incrementing

```
010
010
010
```

produces

```
010
9
10
```

Values with leading zeros and containing 8 or 9 turn into floats instead:

```
08
08
08
```

becomes

```
08
9.0
10.0
```

**Comment by krasa** [comment]
it needs a serious reimplementation
https://github.com/krasa/StringManipulation/issues/17
