### ISSUE TITLE
Aligning Tables without Removing Leading Indent

### ISSUE THREAD

**Issue by iamrecursion** [krasa/StringManipulation#104]
**Is your feature request related to a problem? Please describe.**
My company code style usually mandates vertical alignment of alike operators (e.g. lining up `=`), and I was hoping that String Manipulation could help with this. However, I don't seem to be able to get the alignment I want. Consider the following code:

```
        let mut state_stack = Vec::new();
        let epsilon_links = Vec::new();
        let links = Vec::new();
        let name = Some(String::from("ROOT"));
        let init_state = State{epsilon_links,links,name};
```

When I select this code and use "Align -> Align/Sort Lines by Columns", the combination of "Trim values" and "Add space before separator" gives me the alignment I want, but unindents the code back to the left margin. This is undesirable.

```
let mut state_stack = Vec::new();
let epsilon_links   = Vec::new();
let links           = Vec::new();
let name            = Some(String::from("ROOT"));
let init_state      = State{epsilon_links,links,name};
```

Furthermore, if I don't use "Trim values", but do use "Add space before separator", I end up with two spaces before the separator (`=` in this case). 

```
        let mut state_stack  = Vec::new();
        let epsilon_links    = Vec::new();
        let links            = Vec::new();
        let name             = Some(String::from("ROOT"));
        let init_state       = State{epsilon_links,links,name};
```

**Describe the solution you'd like**
Adapt the "Add space before separator" option to add the space only if it isn't already present.

**Describe alternatives you've considered**
Alternatively, an additional option could be added that maintains leading indentation at the minimum indentation of the selected lines.

**Comment by krasa** [comment]
Done, you can try it if you want:
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/5047469/StringManipulation.zip)

**Comment by iamrecursion** [comment]
This is absolutely fantastic and works perfectly! Thank you so much! I can't wait until it launches in the plugins directory.

**Comment by krasa** [comment]
Thank you! Very generous of you.

**Comment by iamrecursion** [comment]
I've been using this more this morning and it's such a time saver, so thank you again. :D
