### ISSUE TITLE
Align/Sort by Columns does not consider SBC case

### ISSUE THREAD

**Issue by yongfa365** [krasa/StringManipulation#106]
**Describe the bug**
Align/Sort by Columns does not consider SBC case

**To Reproduce**
我 length is 2 not  1

**Expected behavior**
我  length is 2

**Screenshots**
![image](https://user-images.githubusercontent.com/5117787/90505661-94b4d380-e185-11ea-92f6-c4ce58fbbbd6.png)

**Length calc:**
jshell> "我1".length()
$1 ==> 2

jshell> "我1".replaceAll("[^\\x00-\\xff]","aa").length()
$2 ==> 3

**test case**
            "1这个是A | 这个是B | 这个是C",
            "1这个是A   | 这个是B | 这个是C",
            "1这个是A     |     这个是B | 这个是C",
            "1这个是A | 这个是B     | 这个是C",
            "1这个是A | 这个是B | 这个是C",
            "1        | 1    | 2",
            "-1     | 1    | 0",
            "-1      | 0    | -1",

**Comment by krasa** [comment]
Isn't the issue rather that the font has not the same width for all characters? 
Even if you would add extra spaces, it would not align exactly and block selection would not work correctly.

![image](https://user-images.githubusercontent.com/1160875/90509457-a41e2780-e159-11ea-8592-db36e75ab7c7.png)

**Comment by yongfa365** [comment]
Most of the time, the same width font is only for one type of font。

ex：1234abc or 我是谁

It doesn't apply to all fonts at once。My IDE‘s fonts all can't do it
![image](https://user-images.githubusercontent.com/5117787/90590674-b9f02300-e213-11ea-9acc-7b504b1b9c67.png)

Even with a font like this, the display will be poor：
![image](https://user-images.githubusercontent.com/5117787/90591083-bf9a3880-e214-11ea-9500-27ab8e749ff8.png)


so I suggest adding an option in UI:monospace，let user choise，and calc use："我1".replaceAll("[^\x00-\xff]","aa").length()

**Comment by yongfa365** [comment]
Similar problem：https://github.com/krasa/StringManipulation/issues/55
