### ISSUE TITLE
Swapping quotes with no selection leaves line selected, causing text to be lost when you continue typing afterwards

### ISSUE THREAD

**Issue by unikitty37** [krasa/StringManipulation#107]
**Describe the bug**
When I swap between `"` and `'` with nothing selected, the whole line is selected and processed, but is then left selected. The next character typed then replaces the whole line.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter a line of text containing quotes, such as `puts "EXAMPLE"`
1. Put the cursor on the line. Do not select any text.
1. Invoke `Swap " and '` using your preferred method.
1. Type `, 'MESSAGE'`

**Expected behaviour**
After the quotes are swapped, the line is deselected once more so I can continue typing. The line of text now reads `puts 'EXAMPLE', 'MESSAGE'`

**Actual behaviour**
As the line is left selected, it is erased and replaced with the `,` which is the first character typed. The line of text ends up as `, 'MESSAGE'`.

**Environment :**
```
RubyMine 2020.2.2
Build #RM-202.7319.53, built on September 15, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 24
Registry: editor.skip.copy.and.cut.for.empty.selection=true, editor.maximize.on.double.click=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.wix.sasslint, com.mallowigi, com.paperetto.dash, net.seesharpsoft.intellij.plugins.csv, NodeJS, com.intellij.plugins.html.instantEditing, org.jetbrains.plugins.vue, ru.adelf.idea.dotenv
```

**Additional context**
~~It's particularly annoying if the cursor was in the middle of the line, as pressing ← clears the selection and moves the cursor to the beginning of the line, and pressing → clears the selection and moves the cursor to the end of the line, but the only way to get it back where it was is to use the mouse or press the cursor keys a load of times.~~ (actually, you can press `Esc` to clear the selection without moving the cursor)

Leaving the selection as it was is fine when there *is* a selection — but if there's no selection, then it's a bit confusing to suddenly have one. However, I'm sure there's somebody who relies on this, so maybe this would need to be a configurable option?

Other manipulations may do the same thing, but I'm only using the plugin for quote swapping at the moment.

**Comment by krasa** [comment]
I think it is standard behaviour - like Copy, Toggle Case
