### ISSUE TITLE
Build with IDEA 2020.2

### ISSUE THREAD

**Issue by detunized** [krasa/StringManipulation#108]
Hi! 

First, thanks for the cool plugin. I've been trying to contribute and implement some C# related features for the Rider IDE. I faced the problem that I could not build it with the latest IDEA (2020.2). I get `java: package com.intellij.openapi.editor does not exist` all over the place. I'm guessing the plugin SDK could not be found for some reason. Have you tried to build with one of the later IDEs? What is you build environment?

**Comment by krasa** [comment]
You need to use an IntelliJ Platform Plugin SDK, not JDK:
![image](https://user-images.githubusercontent.com/1160875/97122605-5f99a400-1727-11eb-82fd-3a9020e31cf8.png)
![image](https://user-images.githubusercontent.com/1160875/97122693-10a03e80-1728-11eb-8c1d-4a516ae0735d.png)

**Comment by detunized** [comment]
Thanks a lot. That helped. I can build it now.

**Comment by detunized** [comment]
Another question: how do you run and debug this with a test IDE? I will later added this to the README and submit a PR for other people to be able to start easier. Thanks.

**Comment by krasa** [comment]
I uploaded a run configuration profile https://github.com/krasa/StringManipulation/commit/fba890d7b9ecbc2f3578ed72381a4feb6741444f, so it should be just a matter of making SDK from now on.

![image](https://user-images.githubusercontent.com/1160875/97159649-7964d680-177b-11eb-811c-5b2c261bc51f.png)

I documented it in other plugin, it is pretty much same: https://github.com/esteinberg/plantuml4idea#developer-notes

**Comment by krasa** [comment]
also some info is there: https://jetbrains.org/intellij/sdk/docs/basics/getting_started/using_dev_kit.html

**Comment by detunized** [comment]
I was able to start quickly thanks to your responses. I have the basic functionality for C# escaping ready. I need to add unescape as well for completeness. I'll test it locally for a couple of days and will create a PR. I would be cool if you could merge and release. Thanks for your help and for the project! I'm using it daily.
