### ISSUE TITLE
To ASCII

### ISSUE THREAD

**Issue by icaine** [krasa/StringManipulation#11]
Hi, could you please add feature to convert a string to ASCII?

E.g.:
"Česká republika" -> "Ceska republika"
"ěščřžýáíé" -> "escrzyaie"

**Comment by crrash** [comment]
+1

**Comment by krasa** [comment]
:+1:

**Comment by krasa** [comment]
This seems to work best http://stackoverflow.com/a/22646013/685796

**Comment by krasa** [comment]
done

**Comment by icaine** [comment]
thank you very much:)
