### ISSUE TITLE
Quote shifting: search outwards for the quotes if they're not included in the selection

### ISSUE THREAD

**Issue by Ariane-B** [krasa/StringManipulation#115]
**Is your feature request related to a problem? Please describe.**
When I want to swap the quotes on a string (Wrap or Shift between " and ' and `), it's a hassle to select the actual quotes. Sometimes I just want to double-click the string itself (it's often a single word or close to that) and swap. But I can't, because for the command to work, the actual quote characters have to be within my selection. Using the command adds a second layer of quotes.

I don't think "add quotes if none are found" is the best fallback behaviour. If people want to add quotes where they aren't, they're likely to select the text and simply insert a quotation mark. The default behaviour for that is already to wrap the selection in quotes.

**Describe the solution you'd like**
If my selection doesn't begin and end with quotes and I run (Wrap or Shift between " and ' and `), the command would try to factor in additional characters on both sides of the selection until it finds matching quotes. And if it does, it would run the command on that expanded text instead of adding a second layer of quotes.

**Describe alternatives you've considered**
Maybe a macro could do the trick, but I'm honestly not good enough with macros. Are they even capable of that kind of conditional "smart" behaviour?

**Additional context**
Here's what happens currently.

1. Select some text by double-clicking it.
![image](https://user-images.githubusercontent.com/6244273/97999512-683e4a00-1db9-11eb-9ca9-593a47264888.png)
2. Run (Wrap or Shift between " and ' and `). A new layer of quotes is added.
![image](https://user-images.githubusercontent.com/6244273/97999721-b05d6c80-1db9-11eb-9300-36fda75afee1.png)

Here's what I wish happened:
1. Select some text by double-clicking it.
![image](https://user-images.githubusercontent.com/6244273/97999512-683e4a00-1db9-11eb-9ca9-593a47264888.png)
2.  Run (Wrap or Shift between " and ' and `). The quotes outside the selection are changed to backticks.
![image](https://user-images.githubusercontent.com/6244273/97999883-df73de00-1db9-11eb-9ce5-795c7ef68559.png)

This already happens smartly if I put my cursor inside a string without selecting anything and use (Wrap or Shift between " and ' and `), so I guess it would just be a matter of applying that behaviour to selections that don't include quotes, too!

**Comment by krasa** [comment]
Thanks!  
You can try it by installing this (without unzipping) https://github.com/krasa/StringManipulation/releases/download/8.7.191.000.0/StringManipulation.zip

**Comment by Ariane-B** [comment]
Hi! That was fast! Thank you very much.

This works well! However it alters the selection. Not a big deal.
