### ISSUE TITLE
Support "To snake_case" action

### ISSUE THREAD

**Issue by Ghedeon** [krasa/StringManipulation#116]
Similarly to `To camelCase`, would be handy to have a `To snake_case` action. 

One of the possible applications would be a common case in android development where it's possible to have an xml string `"dialog.request_money.title"` that translates by compiler into `R.string.dialog_request_money_title`. Therefore, `To snake_case` comes in handy for searching/editing of this type of strings.

**Comment by Ghedeon** [comment]
Fastest PR I've ever seen :). Thank you.

**Comment by krasa** [comment]
No problem. You can update.

**Comment by Ghedeon** [comment]
@krasa Just tested `8.8.191.000.0`, seems like `To SCREAMING_SNAKE_CASE` is working for the mixed strings but not the `To snake_case`.

Ex:
```
SCREAMING_SNAKE_CASE("lorem.ipsum_dolor.sit") --> "LOREM_IPSUM_DOLOR_SIT"
snake_case("lorem.ipsum_dolor.sit") --> "lorem.ipsum_dolor.sit" // no effect
```

**Comment by krasa** [comment]
Try it now.

**Comment by Ghedeon** [comment]
Worked like a charm. Appreciate it 👍
