### ISSUE TITLE
Case conversion not working for Georgian

### ISSUE THREAD

**Issue by vovchisko** [krasa/StringManipulation#119]
**Describe the bug**
Georgian text won't transform `UPPER CASE / lower case`.

**To Reproduce**
Try to make an `UPPER CASE` for Georgian text and back from examples below:

- Lower case: შეარჩიე კატეგორიების მიხედვით

- Upper case: ᲨᲔᲐᲠᲩᲘᲔ ᲙᲐᲢᲔᲒᲝᲠᲘᲔᲑᲘᲡ ᲛᲘᲮᲔᲓᲕᲘᲗ

> NOTE: most of the mono-fonts usually not support Georgian Case (or Georgian at all) - for example: `ᲛᲘᲮᲔᲓᲕᲘᲗ` is actually caps (ᲛᲘᲮᲔᲓᲕᲘᲗ). I'm using the font `Ayuthaya` that supports Georgian cases.

**Expected behavior**
"შეარჩიე" converts into "ᲨᲔᲐᲠᲩᲘᲔ" and back.

**Screenshots**
Not applicable.

**Environment :**
(But it actually never worked)
```
WebStorm 2020.2.3
Build #WS-202.7660.23, built on September 30, 2020
Licensed to Volodymyr Ishchenko
Subscription is active until April 25, 2021
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.vincentp.gruvbox-theme, tv.twelvetone.intellij.plugins.intellivue, ru.adelf.idea.dotenv
```
**Additional context**
I'm using an online solution for it - https://convertcase.net/ this one works fine. But it's a very boring process copypasting.

**Comment by krasa** [comment]
Dunno how to implement this. It has something to do with locale. You could try to set one for the IDE process, then it could work. But I tried it myself and either I did something wrong or it just does not work and requires some custom solution https://stackoverflow.com/a/24765117/685796.

**Comment by krasa** [comment]
It seems that the support was added to JDK 12
http://hg.openjdk.java.net/zgc/zgc/rev/f94ac11610b3#l1.95
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8212120

Theoretically JB could merge it to their JDK, I will report an issue. 
Or I could probably just parse unicode table http://unicode.org/Public/UNIDATA/UnicodeData.txt and uppercase according to that.

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/JBR-2875

**Comment by vovchisko** [comment]
Oh, I noticed you step on it too 😄  - when you format `code block` in markdown - both upper and lower case in Georgian show as lowercase. (see `note` in bug description)

**Comment by krasa** [comment]
works fine for me :)
![image](https://user-images.githubusercontent.com/1160875/99689442-4b776700-2a87-11eb-8809-d8607a394ec8.png)

**Comment by vovchisko** [comment]
🤨 Hmmm... And seems some fallback-font, (I see it because it's not monospaced).

**Comment by krasa** [comment]
IJ 2022 runs on JDK 17, it works.
