### ISSUE TITLE
JSON minify not preserving element order

### ISSUE THREAD

**Issue by markfalk** [krasa/StringManipulation#120]
**Describe the bug**
The minify option is not preserving element order

**To Reproduce**
1. Use the minify on a simple json

**Expected behavior**
This:
```
{
  "b": "b",
  "a": "a"
}
```
should minify to:
```
{"b":"b","a":"a"}
```
instead it minify's to:
```
{"a":"a","b":"b"}
```
**Environment :**
Running version: 8.9.191.000.2

**Comment by krasa** [comment]
https://github.com/stleary/JSON-java/issues/571

**Comment by markfalk** [comment]
I'm not implying that the json is "wrong", just that every other minify tool I have used always maintains the order of elements.  I would like it to at least be an option.
https://codebeautify.org/jsonminifier
https://onlinejsontools.com/minify-json

thanks.
