### ISSUE TITLE
Hierarchical sort with JSON kind of loses the final closing braces

### ISSUE THREAD

**Issue by WillGibson** [krasa/StringManipulation#122]
If I get a chance I'll try and submit a pull request for this.

**Describe the bug**
When sorting JSON object properties with Hierarchical sort each element's closing brace kind of comes adrift.

**To Reproduce**
1. Try sorting something like this ascending with the Heirachical sort...
```
      "X-Correlation-ID": {
        "$ref": "components/parameters/X-Correlation-ID.json"
      },
      "Authorization": {
        "$ref": "components/parameters/Authorization.json"
      },
```
2. Results in...
```
      "Authorization": {
        "$ref": "components/parameters/Authorization.json"
      "X-Correlation-ID": {
        "$ref": "components/parameters/X-Correlation-ID.json"
      },
      },
```

**Expected behavior**
We would expect this result...
```
      "Authorization": {
        "$ref": "components/parameters/Authorization.json"
      },
      "X-Correlation-ID": {
        "$ref": "components/parameters/X-Correlation-ID.json"
      },
```

**Screenshots**

![image](https://user-images.githubusercontent.com/8738245/104931519-6dfe0180-599e-11eb-8797-5cd004b287bb.png)

![image](https://user-images.githubusercontent.com/8738245/104931580-7fdfa480-599e-11eb-8880-2588d3125606.png)

**Environment :**
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Licensed to REDACTED
You have a perpetual fallback license for this version.
Subscription is active until December 1, 2021.
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: com.intellij.ideolog, com.jetbrains.ChooseRuntime, com.intellij.plugins.watcher, com.jinsihou.react.snippets, com.ultrahob.zerolength.plugin, indent-rainbow.indent-rainbow, org.jetbrains.plugins.rest, mobi.hsz.idea.gitignore, AWSCloudFormation, org.zalando.intellij.swagger, String Manipulation, com.kaylerrenslow.plugin.armaplugin.id, org.jetbrains.plugins.hocon, com.jetbrains.lang.ejs, cucumber-javascript, intellij.prettierJS, com.dmarcotte.handlebars, com.intellij.react.css.modules, org.jetbrains.plugins.vue, tv.twelvetone.intellij.plugins.intellivue, org.jetbrains.kotlin, org.intellij.scala, com.jetbrains.php, com.jetbrains.twig, org.jetbrains.plugins.ruby, Pythonid, aws.toolkit, ru.adelf.idea.dotenv

**Additional context**

**Comment by krasa** [comment]
Hmm, I did not intend it for such case but it probably could be done.

**Comment by WillGibson** [comment]
It so nearly works, still way quicker to put the closing braces back than do it manually, for which you have my gratitude.

**Comment by WillGibson** [comment]
@krasa I've followed the build instructions in the README. What commands do I need to run to get the tests running locally so I can have a swipe at making it work for this use case?

**Comment by krasa** [comment]
Just right click on it 
![image](https://user-images.githubusercontent.com/1160875/105214362-32a33480-5b50-11eb-90b5-795ff26d5c97.png)

**Comment by WillGibson** [comment]
I made a failing test and I can see how this could be really tricky!

I had a look around specifically for sorting JSON and [JSON Sorter](https://plugins.jetbrains.com/plugin/11104-json-sorter) exists and works well for the JSON use case, so no point reinventing the wheel :-)
