### ISSUE TITLE
Feature Request: Unicode Normalization

### ISSUE THREAD

**Issue by zedseven** [krasa/StringManipulation#124]
Working with a lot of Unicode characters from potentially many sources, I've lately found myself performing [Unicode normalization](https://www.unicode.org/faq/normalization.html) on text a lot.

It would be useful to be able to perform the various Unicode normalization forms on text directly in-editor, without having to copy it elsewhere then paste in the normalized version. In my particular case this is Form D, but I can see uses for all 4 forms.

This isn't a pressing matter by any means but I thought I'd suggest it since there seems to be a [built-in method group](https://docs.oracle.com/javase/tutorial/i18n/text/normalizerapi.html) for this exact purpose in Java already.

**Comment by krasa** [comment]
`Convert Diacritics (Accents) to ASCII` is not doing what you need?

**Comment by zedseven** [comment]
Ah, no - Unicode normalization does things like decompose characters into their component parts:
`á` (`U+E1`) -> `á` (`U+61 U+0301`)
and converting characters into their canonical forms if necessary:
`ʹ` (`U+0374`) -> `ʹ` (`U+02B9`)

**Comment by krasa** [comment]
I see. Adding a new action would be fine. Althought I am thinking that it could be a good idea to use icu4j (unfortunately 13MB jar) beucase JRE 11 Unicode support is limited. https://youtrack.jetbrains.com/issue/JBR-2875

**Comment by krasa** [comment]
I do not really work with unicode that often, so it seems to me useful to see what happens exactly. What do you say to this?
![image](https://user-images.githubusercontent.com/1160875/109519277-6193bb00-7aab-11eb-9fc6-669a0491d643.png)

**Comment by krasa** [comment]
For your example:
![image](https://user-images.githubusercontent.com/1160875/109521159-4cb82700-7aad-11eb-8592-28b038e40acf.png)

**Comment by zedseven** [comment]
That looks fantastic. From what I can see, everything looks good there.

**Comment by krasa** [comment]
You can try it: 
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/6063966/StringManipulation.zip)

Btw is your IDE version 2020.3+?

**Comment by zedseven** [comment]
This is fantastic!
I just tried it with Rider EAP 4 2021.1, and everything seems to be working perfectly.
Thank you so much.
