### ISSUE TITLE
Increment Group as a whole

### ISSUE THREAD

**Issue by benjamw** [krasa/StringManipulation#13]
I tried selecting a large block of text with numbers in it and was hoping it would increment the whole lot, but alas, it did not.

Here is what I was hoping for:

This is what I have
```
<tr>
    <td><?php echo $var['excerpt_1']; ?></td>
    <td><?php echo $var['excerpt_2']; ?></td>
    <td><?php echo $var['excerpt_3']; ?></td>
</tr>
```

I selected the whole table row and hit "Duplicate and Increment" and was hoping for this
```
<tr>
    <td><?php echo $var['excerpt_1']; ?></td>
    <td><?php echo $var['excerpt_2']; ?></td>
    <td><?php echo $var['excerpt_3']; ?></td>
</tr>
<tr>
    <td><?php echo $var['excerpt_4']; ?></td>
    <td><?php echo $var['excerpt_5']; ?></td>
    <td><?php echo $var['excerpt_6']; ?></td>
</tr>
```

but what I got was this
```
<tr>
    <td><?php echo $var['excerpt_1']; ?></td>
    <td><?php echo $var['excerpt_2']; ?></td>
    <td><?php echo $var['excerpt_3']; ?></td>
</tr>
<tr>
    <td><?php echo $var['excerpt_2']; ?></td>
    <td><?php echo $var['excerpt_3']; ?></td>
    <td><?php echo $var['excerpt_4']; ?></td>
</tr>
```

Any chance of adding that to the options somehow?

Or is there a way to do this that I'm not aware of?

**Comment by krasa** [comment]
You could use 'Increment to build sequence' and then 'Decrement'.

**Comment by benjamw** [comment]
That works, but is not very intuitive. Thanks for pointing it out.

**Comment by krasa** [comment]
Yep, what about making 'Increment to build sequence' not increment the first value. So you can quickly duplicate lines with ctrl+D and then use  'Increment to build sequence'?

**Comment by krasa** [comment]
Changes:
- added new action: Increment duplicate numbers ("1 3 3" => "1 3 4")
- replaced 'Increment to produce unique sequence' to 'Create Sequence' ("1 5 0" => "1 2 3")

That should cover it.
