### ISSUE TITLE
Cannot resolve symbol after installing this plugin

### ISSUE THREAD

**Issue by bmel** [krasa/StringManipulation#135]
This happened to me for classes in std java packages: (java.lang, java.io, ...) 
**right after installing the String Manipulation plugin**, on 16 April 2021, version 8.15.203.000.2
Clearing caches/restarting did not help.

**Disabling this plugin 'fixed' the issue for me.**

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: analyze.exceptions.on.the.fly=true

Could be this issue: https://youtrack.jetbrains.com/issue/IDEA-266763

Otherwise, fantastic plugin, waiting anxiously for a resolution.
Happy to provide more info if required.

**Comment by krasa** [comment]
I do not think it is related to this plugin.

**Comment by krasa** [comment]
I had a gradle project like that too, but after reindexing it works even with String Manipulation and I can't reproduce it anymore.

**Comment by bmel** [comment]
I tried at least twice (reindex/restart), did not help. This is echoed by another IDEA user at  https://youtrack.jetbrains.com/issue/IDEA-266763

For me, the unresolved symbols are all in std Java libs (java.lang.String etc), for every of 'my' classes that I open in the editor.
Could it be some clash between JDKs versions?

**Comment by krasa** [comment]
I don't see how the plugin could cause this, especially without even using its actions.

**Comment by krasa** [comment]
do you have some open source project that does it?

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/IDEA-267185#focus=Comments-27-4848228.0-0

**Comment by bmel** [comment]
This time, reindexing has solved the problem for me as well.
I'm thrilled to be able to use your plugin from now on, thank you.
Should I close this issue?
