### ISSUE TITLE
Return the filtering of menu items as you type

### ISSUE THREAD

**Issue by mekras** [krasa/StringManipulation#136]
**Is your feature request related to a problem? Please describe.**

In previous versions, it was possible to filter items in the context menus by entering part of their names. There was no need to memorize the item number or search for it in the list for a long time. It was enough to start typing letters. In one of the previous versions, this feature was removed from the top-level menu. It became less convenient, but tolerable. I used the "Change case" option most often, so it wasn't difficult to remember a single digit. But now, in the second-level menus, filtering has been replaced with numbers. It became quite inconvenient to use — you have to search for the right item for a long time among two dozen options.

**Describe the solution you'd like**

Return it as it was.

**Comment by krasa** [comment]
Do you mean there was a speed search, like this? Maybe before 2014, my git repo does not go farther...
![image](https://user-images.githubusercontent.com/1160875/115540875-cc3cc800-a29e-11eb-9a8d-7eaa935e067e.png)

There was too many actions, so second levels were introduced, For case switching, you can add a shortcut to `Main Menu | Edit | Switch Case...`.


You want it like this or all actions in one long list?
![ggggg](https://user-images.githubusercontent.com/1160875/115542152-46ba1780-a2a0-11eb-90bb-0016a2765720.gif)

**Comment by krasa** [comment]
The search does not work in submenus, It would have to be one long list.
![image](https://user-images.githubusercontent.com/1160875/135449065-bac9f21d-5222-492f-981f-e436c6ae5c49.png)
