### ISSUE TITLE
Feature Request: Sentence case conversion challenge

### ISSUE THREAD

**Issue by JackDandy** [krasa/StringManipulation#138]
Hello,

**Describe the solution you'd like**

Here is a challenge case...
```
this test text forms a MarkDown filE with erroneous mixed case. note this sentence includes valid uppercase for an acronym E.g. and a name Dr. Foster that is on CBC 1 Tonight. this sentence is also e.g. a name dr. foster that is on cbc tomorrow. hint: Edit this exact text in github via FireFox to see how a spellchecker can assist with a solution to processing this test case. 
```

**A clear and concise description of what you want to happen.**

The challenge case to be changed into proper sentence casing...
```
This test text forms a markdown file with erroneous mixed case. Note this sentence has valid uppercase for an acronym E.g. and a name Dr. Foster that is on CBC 1 tonight. This sentence is also e.g. a name Dr. Foster that is on CBC tomorrow. Hint: edit this exact text in GitHub via FireFox to see how a spellchecker can assist with a solution to processing this test case. 
```

I understand that this is not trivial, perhaps even an impossible challenge.

Thank you.

**Comment by krasa** [comment]
imho impossible.
- `e.g.` would be wrong without some dictionary of exclusions
- either `MarkDown` would be left the same, or `CBD` would be lowercased

The best you could have is capitalization of a first letter after `.`

**Comment by krasa** [comment]
Some spellchecker (Grammarly, MS Word) would be better suited.
