### ISSUE TITLE
IDEA 2021.1.1 didn't display the text with underscore correctly

### ISSUE THREAD

**Issue by Coffee0127** [krasa/StringManipulation#142]
**Describe the bug**
using `Popup String Manipulation ...` didn't display the text with underscore correctly.

IDEA 2021.1.1 displays `SCREAMINGSNAKE_CASE`.
<img width="676" alt="2021 1 1" src="https://user-images.githubusercontent.com/4252888/119212708-b7955f00-baec-11eb-86e7-2840f747dede.png">

**To Reproduce**
1. In any editor just trigger the action `Popup String Manipulation ...`
2. Choose `Switch Case...`
3. Sub action menu displays the text.

**Expected behavior**
should display the text as IDEA 2020.3.4 does
<img width="642" alt="2020 3 4" src="https://user-images.githubusercontent.com/4252888/119212711-bb28e600-baec-11eb-8be2-4edecc7c9c69.png">

**Screenshots**
as above

**Environment :**
IntelliJ IDEA 2021.1.1 (Community Edition)
Build #IC-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12

Kotlin: 211-1.4.32-release-IJ7142.27

**Additional context**
* using String Manipulation 8.15.203.000.3
* using right click or select it from menu displays the text correctly
  * From menu
    <img width="1051" alt="2021 1 1 Menu" src="https://user-images.githubusercontent.com/4252888/119213554-828c0b00-baf2-11eb-8474-a0906a582070.png">
  * right click
    <img width="1084" alt="2021 1 1 Right click" src="https://user-images.githubusercontent.com/4252888/119213556-87e95580-baf2-11eb-8c5a-d578df4e1193.png">

**Comment by krasa** [comment]
Platform issue, hopefully it will be fixed. https://youtrack.jetbrains.com/issue/IDEA-269921

**Comment by Coffee0127** [comment]
great, I'll follow that. thanks
