### ISSUE TITLE
Would like an "Align Only" option on "Align\Sort line by columns" the same as the existing "Sort Only" option. 

### ISSUE THREAD

**Issue by arvidj01** [krasa/StringManipulation#146]
**Is your feature request related to a problem? Please describe.**
I would like to align by column but do not want to sort the lines.

**Describe the solution you'd like**
I would select "Align\Sort line by columns", put a ',' in the Separator field, select the "Align Only" box, leave the "Sort Only box" unchecked, and press OK.

Note that any other UI incantation to get alignment without sorting is fine. Just would like the anti-sort feature. 

**Describe alternatives you've considered**
The alternative is to live with sorted lines or use another plugin, like "Vertical Align" or "Column Align", both of which have other idiosyncrasies that may them "less than perfect".

**Additional context**

**Comment by krasa** [comment]
If you do not fill `Sort by columns` field, then it will not sort by anything, so it will in fact align only.

**Comment by arvidj01** [comment]
Makes perfect sense but is not intuitively obvious. Thanks.
