### ISSUE TITLE
High CPU usage in PhpStorm 2021.1 at idle

### ISSUE THREAD

**Issue by adrianguenter** [krasa/StringManipulation#147]
**Describe the bug**
The plugin fully utilizes 1-3 CPU cores indefinitely after loading the IDE. Disabling the plugin (after waiting for settings to load) reduces CPU usage to almost nothing immediately.

**To Reproduce**
1. Start the IDE
2. Observe CPU usage after all background tasks complete

**Expected behavior**
CPU usage drops to minimal levels after background tasks have completed

**Additional context**
String Manipulation 8.15.203.000.3
PhpStorm 2021.1.4 Build #PS-211.7628.25, built on June 30, 2021
Runtime version : 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by krasa** [comment]
please provide a cpu snapshot or at least a threaddump https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems
