### ISSUE TITLE
Option to partition by regex

### ISSUE THREAD

**Issue by daveyostcom** [krasa/StringManipulation#149]
It’s very handy in some situations to be able to partition text. (Speaking from years of experience using a simple unix filter command I made, called grepboth, which does this.)

Note: this is, of course, not useful for editing code. It's for lists of things.

The command should use the contents of the search field to alter the file or selection so that

- blank lines are deleted
- line order is maintained within two partitions, presented thus:
  - matched lines
  - a blank line
  - unmatched lines

**Comment by krasa** [comment]
Is it good? https://plugins.jetbrains.com/plugin-ideas still contains this request

**Comment by daveyostcom** [comment]
Hi, not clear what you’re asking.

**Comment by krasa** [comment]
Hi, I am asking if you are satisfied with the implementation in this plugin :-)

**Comment by daveyostcom** [comment]
> Hi, I am asking if you are satisfied with the implementation in this plugin :-)

Yes, I love the plugin, but I would also love to have the partition feature.  :)

**Comment by krasa** [comment]
It is there :-)
![image](https://user-images.githubusercontent.com/1160875/228159490-f322f499-8d72-488f-bf62-5e70220ca5e8.png)

**Comment by daveyostcom** [comment]
It would also help if you would give Partition its own menu item under the Filter menu.
![image](https://user-images.githubusercontent.com/8748/228160526-3eecf40b-0e26-4575-af85-851b6b41ff26.png)

**Comment by daveyostcom** [comment]
Come to think of it, why not separate section of the main menu with menu items for
- Filter
- Remove
- Trim
- Minify
- Convert
- Partition
