### ISSUE TITLE
request to add swap words feature

### ISSUE THREAD

**Issue by tirams** [krasa/StringManipulation#15]
request for addition of an feature that transposes words around a comma i.e.

callFuncname(aParam, aNotherPararm)

with the caret on a 1st parameter(aParam) a new action swap words would result in transposing the 2 parameters leaving the , in between resulting in :

funcname(aNotherPararm, aParam)

**Comment by krasa** [comment]
IntelliJ already does that, at least for Java, just press alt+enter.... If you need it for another language, it would be best to report it on jetbrains site.
