### ISSUE TITLE
Support shuffling characters

### ISSUE THREAD

**Issue by G-Rath** [krasa/StringManipulation#150]
**Is your feature request related to a problem? Please describe.**
I commonly find myself needing to shuffle the characters in a string, such as when I'm writing fake data for tests for properties like IDs.

**Describe the solution you'd like**
A "shuffle characters" option next to the "shuffle lines" option, that shuffles the selected text.

**Describe alternatives you've considered**
Manually shuffling the characters.

**Additional context**
None that I know of.

**Comment by krasa** [comment]
wouldn't be better to have a generator?

**Comment by G-Rath** [comment]
I see value in both: I imagine a generator would be more complex and require more input from the user (since you'd need to have a UI for providing specifics like length, types of characters to include, etc) whereas "Shuffle selected" I would expect should be a lot more straightforward, being mostly copyable from "Shuffle lines".
