### ISSUE TITLE
Re-Add the InvertedGrepAction?

### ISSUE THREAD

**Issue by janjan** [krasa/StringManipulation#152]
I was happily using "Inverted Grep" from the StringManipulation plugin to efficiently clean up log files

Unfortunately my workflow "broke" after this commit https://github.com/krasa/StringManipulation/commit/396aec58cb53e12c9d15627b1e748db2c7272982 because it removed InvertedGrepAction

My workflow was as follows:

- I had a shortcut to "inverted grep" bound to ctrl+del
- When I wanted to clean up a log file from useless logs I selected a part of a useless log entry and pressed ctrl+del to remove that sort of log from the whole file. I repeated this a few times to remove all trash logs and ended up with a nice and clean log file

After the last update I had to re-assign my shortcut to just "Grep". In theory this offers the same functionality as before but in practice I am slightly annoyed by the popup dialog because I don't really need it. 

I'd prefer to just select some words, press a short cut and then all lines with those words are removed from the whole file.

Is there any chance to re-add dialog-less grepping?

Thanks for your awesome work! :)

**Comment by krasa** [comment]
Thank you!
