### ISSUE TITLE
quote/unquote feature

### ISSUE THREAD

**Issue by MohammadMD1383** [krasa/StringManipulation#155]
ability to quote / unquote a word or selection.

`|` -> cursor
`()` -> selection
```
so|me word -> action performed -> "some" word
"so|me" word -> action performed -> some word

(some word) -> action performed -> "some word"
and ...
```

**Comment by krasa** [comment]
Perhaps I will have to tune or add settings for expanding selection, there might be some edge cases.

You can try it:
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/7449527/StringManipulation.zip)

**Comment by MohammadMD1383** [comment]
Thank you so much!👌
