### ISSUE TITLE
Grep only works on first 100k characters

### ISSUE THREAD

**Issue by nikess** [krasa/StringManipulation#156]
First, thanks for great plugin.

But grep only works for 100k characters, is there a fixed buffer perhaps?

Appreciate if you can remove the limit entirely please.

**To Reproduce**
Use a file with > 100k characters, grep a simple term beyond 100k boundary, it is missing in grep output

**Expected behavior**
Appears in output

**Comment by krasa** [comment]
The only buffer is in the IntelliJ console itself. `File | Settings | Editor | General | Console`

**Comment by nikess** [comment]
I should have been clearer - apologies - my repro steps are on a scratch file, not console.

**Comment by krasa** [comment]
So how do you grep it? You Tail it and grep from its console?

**Comment by krasa** [comment]
I see, I thought I am in Grep Console plugin :-)
I will check it.

**Comment by krasa** [comment]
There is a limit of 100k for the grep preview, for performance reasons. Is the issue only the preview?

**Comment by nikess** [comment]
Yes, it turns out its only the preview - thanks for the help there.  (Perhaps consider a note in the preview to say its limited to 100k?).  Thanks again.
