### ISSUE TITLE
Replace With Spaces

### ISSUE THREAD

**Issue by daveyostcom** [krasa/StringManipulation#158]
Replaces every selected character with a space.

Sometimes I want to delete some code but not change the position of text to its right.

**Comment by krasa** [comment]
it can be done pretty easily already
![image](https://user-images.githubusercontent.com/1160875/141836558-d1e30f2d-0416-4701-9721-648844d362ab.png)

**Comment by daveyostcom** [comment]
Of course.  Replace All.  :)
