### ISSUE TITLE
Deduplicate lines

### ISSUE THREAD

**Issue by studersi** [krasa/StringManipulation#159]
**Is your feature request related to a problem? Please describe.**
Sometimes there are duplicate lines after sorting because people added lines at the bottom without checking if they were already present. They become apparent once the lines are sorted but must then be removed manually

**Describe the solution you'd like**
It would be nice to have an action to deduplicate lines. Also, it would be nice to have an additional action to deduplicate automatically after sorting.
* Deduplicate lines
* Sort Lines and Deduplicate

**Comment by krasa** [comment]
![image](https://user-images.githubusercontent.com/1160875/142459536-5a311b88-4a78-4056-9a7a-f920f8062f6d.png)

**Comment by studersi** [comment]
Oh, my bad... Was this feature added recently? I remember looking for it a few days ago but now I see it as well.

**Comment by krasa** [comment]
No, it is pretty old afaik.

**Comment by studersi** [comment]
Well, thanks for pointing this out :-)
