### ISSUE TITLE
Feature request: Snake_Case_With_Capitalised_Words

### ISSUE THREAD

**Issue by tjhleeds** [krasa/StringManipulation#161]
**Is your feature request related to a problem? Please describe.**
The convention for unit test names at my company is to use Snake_Case_With_Capitalised_Words. Using this plugin I can either capitalise all the words with spaces between them, or make them snake case in all lower case.

**Describe the solution you'd like**
The ability to manipulate a string to Snake_Case_With_Capitalised_Words.

**Describe alternatives you've considered**
- A way to configure the behaviour of the existing snake_case functionality to specify whether or not the case of the words should be changed, or to specify that they should be all lowercase/first word capitalised/first letter of each word capitalised. (We already have the option for all capitalised by using SCREAMING_SNAKE_CASE.)

**Comment by krasa** [comment]
example of the input you want to transform to Snake_Case_With_Capitalised_Words?

**Comment by tjhleeds** [comment]
I would use one of two approaches which suit my typing style.

I might start with a comment like this:
`public async Task //should be able to search without filtering based on bonded stock holdings()`
This is quick for me to type as it's just natural language. I'd highlight the words from `should` to `holdings` and trigger the string manipulation, then remove the `//` comment symbols.

Alternatively I would type a single long word to avoid the need to uncomment afterwards:
`public async Task ShouldBeAbleToSearchWithoutFilteringBasedOnBondedStockHoldings()`
I would then highlight that word and trigger the string manipulation.

In either case, I'd want this output:
`public async Task Should_Be_Able_To_Search_Without_Filtering_Based_On_Bonded_Stock_Holdings()`

It slows down my typing a lot to try and reach up for the underscore key (because I'm a fast typist with letters but never really learnt how to properly touch type the numbers & symbols on my keyboard), so the aim is to avoid typing that character repeatedly.

**Comment by krasa** [comment]
You can try it
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/7660692/StringManipulation.zip)

**Comment by tjhleeds** [comment]
Brilliant, thanks!
