### ISSUE TITLE
Add shortcut prevents use of "repeat last action"

### ISSUE THREAD

**Issue by kittle31** [krasa/StringManipulation#163]
**Describe the bug**
The new "add shortcut" option prevents the existing "repeat last action" from working.

**To Reproduce**
1. select something 
2. Pick "string manipulation" from context menu.
3. perform some action in the menu, ex: "switch to lowercase"
4. close menu.
5. repeat step 1 & 2
6. Attempt to select 1st menu option "Repeat  - To lower case"
7. Option is non-functional.  instead there is a sub-menu for "add shortcut"

**Expected behavior**
The existing first menu option "repeat last action" should function

**Environment :**
Intellij ultimate 2021.1 running on ubuntu 18
string manipulation v: 8.24.203.5981.1

**Comment by krasa** [comment]
thanks, it worked only from alt+m popup, which is what I use.

**Comment by krasa** [comment]
you can update

**Comment by krasa** [comment]
Perhaps I should ungroup it, I do not like that it requires an extra click.

**Comment by kittle31** [comment]
Un-grouping would be much appreciated.
Maybe you can put the create shortcut as the 2nd menu item.  Then muscle memory wont be picking the wrong option

**Comment by krasa** [comment]
Should be good now.
