### ISSUE TITLE
Paste multiple lines (clipboard) as PHP array of strings

### ISSUE THREAD

**Issue by BrutusBossNL** [krasa/StringManipulation#164]
Since we're doing a lot of database migrations (and so wirting them in Laravel), it would be nice to paste the copied table column names (multi line string) directly as a PHP Array of strings.

Like this:

__Copied:__
```
id
name
descirption
```

__Paste as:__
```php
[
    'id',
    'name',
    'description',
]
```

**Comment by krasa** [comment]
You can try it;
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/7838403/StringManipulation.zip)
![image](https://user-images.githubusercontent.com/1160875/148757192-65234760-48ca-4c29-9512-04155c4af566.png)

**Comment by BrutusBossNL** [comment]
Tested and validated. Works like a charm!

Your speed is very much appreciated!
