### ISSUE TITLE
Support for C++ conversion to/from raw string literal

### ISSUE THREAD

**Issue by stribor** [krasa/StringManipulation#166]
When dealing with lots of escape sequences in strings, it would be nice if there was possibility to do conversion to and from raw string literals.

So I would like to be able to convert from:
```C++
const char* s1 = "a\\b\\c\\d";

const char* s2 = "\nHello\n  World\n";
```
to
```C++
const char *s1 = R"(a\b\c\d)";

const char* s2 = R"foo(
Hello
  World
)foo";
```
and back

In s2 case, the `foo` could be any string or omitted, possibly config option. 

In CLion I have sometimes the following inspection "Clang-Tidy: Escaped string literal can be written as a raw string literal" that does conversion to raw string (i.e. happens in case of first s1, but not in case s2), and there is no option to go back to escaped string.

Manual way to do conversion would be to select `a\\b\\c\\d` inside quotes (without quotes) to do copy (CLion automatically unescapes text to clipboard), and then paste text and add `R"(` and `)"` around raw text, and to convert other way would be to select again raw text do copy, and paste it between `""` (CLion automatically escapes pasted text), so possibly quick implementations would be to automatize this.

Possibly other string literal formats could be supported. More info about string literals can be found at https://en.cppreference.com/w/cpp/language/string_literal

**Comment by krasa** [comment]
Making an own intention would be super easy, the problem is proper escape handling, which is something I personally do not want to get into.

**Comment by krasa** [comment]
I will take a look how that copy paste works.

**Comment by krasa** [comment]
It seems CLion uses a generic escaping.
You can try it
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/7865437/StringManipulation.zip)

![image](https://user-images.githubusercontent.com/1160875/149396058-f876b792-dd44-4475-a588-a42f15eadf12.png)

**Comment by stribor** [comment]
Yes! This is what I wanted! Works quite nice!
