### ISSUE TITLE
Extend Selection in Different "CamelHumps" Mode expands too much (e.g. generic type parameters).

### ISSUE THREAD

**Issue by jmiserez** [krasa/StringManipulation#167]
**Describe the bug**
When 'Use "CamelHumps" words' is ON, 'Extend Selection in Different "CamelHumps" Mode' behaves differently from the IntelliJ 'Extend Selection' when 'Use "CamelHumps" words' is OFF. Specifically generic class definitions like `AbstractMyClass<SomeClass>`.

**To Reproduce**
1. Set 'Use "CamelHumps" words' to OFF, and set regular 'Expand selection' to Ctrl-W.
2. Add this line in a .java file:
`public static class MyClass extends AbstractMyClass<SomeClass> {}`
click into `AbstractMyClass` and press Ctrl-W twice.
3. Result: Only `AbstractMyClass<SomeClass> is selected -> **correct**
4. Set 'Use "CamelHumps" words' to ON, and set 'Extend Selection in Different "CamelHumps" Mode' to Ctrl-W (click 'Remove' to remove Ctrl-W from the regular 'Expand Selection')
5. Open a different .java file (important)
6. Add this line in the different .java file:
`public static class MyClass extends AbstractMyClass<SomeClass> {}`
click into `AbstractMyClass` and press Ctrl-W twice.
7. Result: whole line `public static class MyClass extends AbstractMyClass<SomeClass> {}` is selected -> **unexpected**

**Expected behavior**
In step 7, expected only `AbstractMyClass<SomeClass>' to be selected, not the whole line.

**Screenshots**
IntelliJ 'Use CamelHumps' OFF with IntelliJ 'Expand Selection' (Ctrl-W):
![Intellij-Expand-Selection-without-CamelHumps](https://user-images.githubusercontent.com/5045692/149508013-354bfe32-df49-498d-9721-5f1643cd1a89.gif)

IntelliJ 'Use CamelHumps' ON with String Manipulation 'Extend Selection in Different "CamelHumps" Mode':
![StringManipulation-Expand-Selection-in-Different-CamelHumps-Mode-with-CamelHumps](https://user-images.githubusercontent.com/5045692/149508038-5fb1c71f-f7ca-493c-b0b7-bbec5d44a5e6.gif)

**Environment :**
- IntelliJ IDEA 2021.2.3 (Ultimate Edition), Build #IU-212.5457.46, built on October 12, 2021
- String Manipulation (8.24.203.5981.3)

**Comment by krasa** [comment]
Thanks!

**Comment by jmiserez** [comment]
Yes, I verified it now works correctly. Thanks!
