### ISSUE TITLE
The snake_case si showing as snakecase in context menu

### ISSUE THREAD

**Issue by meridius** [krasa/StringManipulation#168]
**Describe the bug**
in the context menu (items 2, 4 and B) the `snake_case` is actually shown as `snakecase`. This can cause certain confusion.

However in Settings it is displaying as it should be.

My guess would be that PhpStorm is trying to do some mnemonic magic, but it didn't quite click.

**To Reproduce**
1. open plugin context menu
2. see that the `snake_case` is actually shown as `snakecase`

**Expected behavior**
The `snake_case` should be shown with underscore to imply how the changed text will look like.

**Screenshots**

![image](https://user-images.githubusercontent.com/372431/149756859-ebea9ae3-490a-4758-94ad-69a5e0318020.png) ![image](https://user-images.githubusercontent.com/372431/149757387-85c43916-6744-44ae-a7cf-1c4e8f460a04.png)

**Environment :**

<details>
<summary>env details</summary>

```
PhpStorm 2021.3.1
Build #PS-213.6461.83, built on December 29, 2021
Licensed to {{censored}}
Subscription is active until {{censored}}
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.16.0-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 1994M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    ide.tooltip.initialDelay=225

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.1)
    org.toml.lang (213.5744.224)
    org.jetbrains.plugins.go-template (213.5744.190)
    name.kropp.intellij.makefile (213.5744.224)
    dev.meanmail.plugin.nginx-intellij-plugin (2021.3-2021.3)
    com.wakatime.intellij.plugin (13.1.8)
    org.intellij.plugins.hcl (0.7.14)
    com.alayouni.ansiHighlight (1.2.4)
    String Manipulation (8.25.203.5981.1)
    Key Promoter X (2021.3)
    mobi.hsz.idea.gitignore (4.3.0)
    de.espend.idea.php.annotation (8.0.0)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    fr.adrienbrault.idea.symfony2plugin (0.23.213)
    com.jantvrdik.intellij.latte (1.1.4)
    NEON support (0.5.1)
    izhangzhihao.rainbow.brackets (6.21)
    ru.adelf.idea.dotenv (2021.3.0.213)

Current Desktop: GNOME
```
</details>

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/IDEA-269921 :(
Sorry, I should have created an issue for that.
