### ISSUE TITLE
Increment/decrement sub-sequences

### ISSUE THREAD

**Issue by giovannibgr** [krasa/StringManipulation#17]
Probably this is not an issue and is already covered somehow, **but** I could not find out how to increment sequences like:
1.1
1.2
1.3...
only at their second (last) portion.

Using Increment/Decrement... I got the following:
2.1
2.2
2.3

Is there a way to increment the minor part instead:
1.2
1.3
1.4

**Comment by krasa** [comment]
No, all you can do is to select minor part only. All operations are unfortunatelly for whole numbers.

**Comment by krasa** [comment]
Fixed by #103
