### ISSUE TITLE
Request : switch case with diacritics conversion

### ISSUE THREAD

**Issue by mgohin** [krasa/StringManipulation#171]
I use a lot the `switch case` option with a shortcut. 

I searched an option to apply any conversion while using the `switch case` like `Escape/Encode > Convert diacritics (accents) to ASCII` but did not found.

I'm french, I use a lot Cucumber and copy paste my Given/When/Then ;)

By the way, thanks for this nice plugin, I use it everyday and it saves me a lot of time.

**Comment by krasa** [comment]
Have you tried Macros? 
Although including Paste + selection of the text into the macro might be problematic.

I recently created `Paste as camelCase` but making something more generic and configurable would not be a problem.

**Comment by krasa** [comment]
I think that simply making a `Paste` action that would keep the selection would be enough, then you could chain everything through macros

**Comment by mgohin** [comment]
Gonna try this, I'll let you know

**Comment by mgohin** [comment]
Hmm all keymaps with `V` are used and useful.

I could search another key to map but I still think it would be great to have that kind of option in your plugin, because everytime I switch case it's for code only (so must remove diacritics).

Maybe it's difficult to do and I can understand that you don't want it ;)

**Comment by krasa** [comment]
I actually like the idea.
You can try it:
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/7995116/StringManipulation.zip)

**Comment by krasa** [comment]
this: [StringManipulation.zip](https://github.com/krasa/StringManipulation/files/7995121/StringManipulation.zip)

**Comment by mgohin** [comment]
THAT'S .... perfect <3
You did apply the ASCII conversion only for some of cases only, p.e.r.f.e.c.t

I must uninstall it for security reason, can't wait the release !

**Comment by krasa** [comment]
you can update

**Comment by mgohin** [comment]
That's great, thx !
