### ISSUE TITLE
sidebar visibility

### ISSUE THREAD

**Issue by ybasefinal** [krasa/StringManipulation#172]
**Is your feature request related to a problem? Please describe.**
what's the usage of the plugin sidebar view? can it be displayed optionally?

**Describe the solution you'd like**
add a configuration to settings to choose whether open this view or not.

**Comment by krasa** [comment]
![image](https://user-images.githubusercontent.com/1160875/153391334-cff1eb7b-bf9d-41ec-95aa-017eb837b792.png)

I will try to figure it out.

**Comment by ybasefinal** [comment]
Currently using this method, but it needs to be set up individually on each project, it would be nice if it could be set up globally.
