### ISSUE TITLE
Swap Words functionality changed?

### ISSUE THREAD

**Issue by Ridiculon** [krasa/StringManipulation#174]
The "Swap Words" functionality behavior has changed for some reason, it no longer swaps two words' positions.

**To Reproduce**
Highlight two words:
![image](https://user-images.githubusercontent.com/1812965/160140682-93a4ce77-8799-4a39-aca1-39508c4eaadd.png)

swaps to:
![image](https://user-images.githubusercontent.com/1812965/160140025-e04fecac-2084-4a16-9891-d097bb2c12fc.png)

**Expected behavior**
Previously if I used multiple cursors to select 2 words it would swap their positions completely; aka WordOne should be on the bottom line and WordTwo should be on the top line after swapping like so ->
![image](https://user-images.githubusercontent.com/1812965/160141035-589d2979-1bc3-4fa2-8c68-21e29a8be500.png)

**Environment :**

> IntelliJ IDEA 2021.3.3 (Ultimate Edition)
> Build #IU-213.7172.25, built on March 15, 2022
> Licensed to ESC 20 / Elijah Clifford
> Subscription is active until September 1, 2022.
> Runtime version: 11.0.14.1+1-b1751.46 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Windows 10 10.0
> GC: G1 Young Generation, G1 Old Generation
> Memory: 4000M
> Cores: 12
> Registry:
>     debugger.watches.in.variables=false
> 
> Non-Bundled Plugins:
>     com.elliotwaite.cyberpunk_theme (1.0.10)
>     net.vektah.codeglance (1.5.4)
>     com.markskelton.one-dark-theme (5.5.1)
>     com.layoutmanager (1.4.0)
>     com.intellij.plugins.vscodekeymap (213.5744.3)
>     com.intellij.javafx (1.0.4)
>     String Manipulation (9.4.0)
>     GrepConsole (12.11.211.6693.0)
>     izhangzhihao.rainbow.brackets (6.21)
>     zielu.gittoolbox (212.8.8)
>     JSR45Plugin (213.5744.125)
> 
> Kotlin: 213-1.6.10-release-961-IJ6777.52

**Additional context**
This functionality is the main draw for this plugin for me, its the only feature I have actually used

**Comment by krasa** [comment]
Doesn't `Swap Characters/Selections/Lines/Tokens` do what you need?

**Comment by Ridiculon** [comment]
Ah! So it does!

That works for me, but is there some reason why that feature got moved from the "Swap Words" (option 9) to C / S / L / T (option 0)? Just out of curiosity

**Comment by krasa** [comment]
`Swap Words` was simply added on top of that old one `Swap Characters/Selections/Lines/Tokens`, not below it. :-)

**Comment by Ridiculon** [comment]
Aaaah hah, i pretty much just use the shortcut instead of looking at it so it caught me out, thanks for the plugin!
