### ISSUE TITLE
Provide option to toggle camelCase to snake_case

### ISSUE THREAD

**Issue by ChillarAnand** [krasa/StringManipulation#175]
<img width="690" alt="Screenshot 2022-04-01 at 11 06 12" src="https://user-images.githubusercontent.com/4463796/161201457-b607f7da-f3bb-4b27-9954-c15edd704046.png">

Currently, there is no option to toggle camelCase to snake_case. Consider including that case as well?

**Comment by krasa** [comment]
this one? 
![image](https://user-images.githubusercontent.com/1160875/163136720-d5752646-e917-4d61-bf96-f66d73115e4e.png)
