### ISSUE TITLE
Add an ID to plugin.xml

### ISSUE THREAD

**Issue by persiliao** [krasa/StringManipulation#176]
I'm writing a plugin, that I want to depend on, but I found the plugin id in plugin.xml and would like to add it

```xml
<idea-plugin>
    <!-- Something like this -->
    <id>krasa.stringmanipulation</id>
</idea-plugin>

```

**Comment by krasa** [comment]
Plugin ID is `String Manipulation`

**Comment by persiliao** [comment]
Thank you, just tested, the original name is also possible
