### ISSUE TITLE
Convert to UPPER and lower case

### ISSUE THREAD

**Issue by noplanman** [krasa/StringManipulation#18]
Would be great to have an action for converting the selected text to upper/lower case.
I don't mean capitalise, I mean change the case of all selected characters.

How do I build your source code to get the plugin .jar file? That way I can play around and maybe PR 😊

**Comment by krasa** [comment]
IntelliJ already does that

**Comment by krasa** [comment]
https://www.jetbrains.com/help/idea/2016.1/toggling-case.html

**Comment by noplanman** [comment]
Ah yes I see, it sometimes needs that command to be called twice to get the desired result, but it works.
Coming from Sublime, it still feels more natural to just say "selection to uppercase" or "selection to lowercase", no matter what the selection is.

So I assume you wouldn't want this in your plugin then?

Thanks for all the other features, sooo helpful! 😃👍

**Comment by krasa** [comment]
There are already so many actions, I think it is better to have one which toggles the case, than two which do the same, but separatelly.  But perhaps JetBrains could make their action to toggle to uppercase first :smile: 
No, I don't see the point for adding it.

My pleasure.  :smiley:
