### ISSUE TITLE
extra blank lines

### ISSUE THREAD

**Issue by gregcousin126** [krasa/StringManipulation#199]
Is it possible to create a function to be able to remove all extra blank lines and not all blank lines ? something like this : https://marketplace.visualstudio.com/items?itemName=rintoj.blank-line-organizer

**Example :** 

``` typescript
// start of file

const Person = {
    item : "item"



}


person.item = "item 1"


// end of file
```

**would end up being :** 

``` typescript
// start of file

const Person = {
    item : "item"

}

person.item = "item 1"

// end of file
```

**Comment by krasa** [comment]
in other words: Remove Consecutive Empty Lines?

**Comment by krasa** [comment]
You can try it
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/10946408/StringManipulation.zip)

**Comment by gregcousin126** [comment]
Exactly, ok great, thanks for the fast response. I'll try it.

**Comment by gregcousin126** [comment]
Would you know when you might be able to publish these changes to JetBrains plugin?

**Comment by krasa** [comment]
yes, now.
