### ISSUE TITLE
The combination Alt+M is called when refactoring

### ISSUE THREAD

**Issue by BorzdeG** [krasa/StringManipulation#2]
step 0: http://habrastorage.org/files/e56/b56/7d3/e56b567d3a9442499d6df65b7acb787d.png
step 1: http://habrastorage.org/files/b8f/e9f/a3f/b8fe9fa3fbe648deaa67c7e0b9e6651b.png

**Comment by krasa** [comment]
it should be fixed now.

**Comment by BorzdeG** [comment]
Yes, fixed. Thank U!
