### ISSUE TITLE
Convert to words in sentence (space separated) option

### ISSUE THREAD

**Issue by hexmind** [krasa/StringManipulation#20]
It will be useful for Spock test method names.

**Comment by krasa** [comment]
Could you be more specific?

**Comment by hexmind** [comment]
This is enhancement proposition to new converter:
eg: 
"someWords" => "some words"
"some-words" => "some words"
"some_Words" => "some Words"

**Comment by krasa** [comment]
It already is possible in `Toggle Case`, so you want a new action into the menu?
Maybe I should change `To camelCase (or to words)` to `To words (or to camelCase)` and without capitalization...

**Comment by hexmind** [comment]
Yes, "or to words" works but without decapitalization.
I think it should has decapitalization because capitalized letter only show parts.
But if you want have back compatibility it should be:
old "To camelCase (Or To Words)" // only label changed
new "To camelCase (or to words)" // with decapitalization
