### ISSUE TITLE
right-aligned numbers

### ISSUE THREAD

**Issue by daveyostcom** [krasa/StringManipulation#203]
I would like a checkbox to right-align numbers.  In this image, see how all the numbers are left-aligned?

![image](https://user-images.githubusercontent.com/8748/228158905-83886466-ac7a-4d20-a1de-a676252546a7.png)

It would be great to be able to right-align them.  Or if the numbers were to have decimal points, to align on the decimal points.

**Comment by daveyostcom** [comment]
Thanks!

**Comment by krasa** [comment]
You can try it:
[StringManipulation-9.11.0.zip](https://github.com/krasa/StringManipulation/files/12208945/StringManipulation-9.11.0.zip)

**Comment by daveyostcom** [comment]
Nice!  And I like the way you did decimal point alignment.

**Comment by krasa** [comment]
Thanks. 
There is a problem when a column contains number+units. 
Not sure if I should add a field for changing the regex `[ ,.\-+]*\d.*` or column indexes
![image](https://github.com/krasa/StringManipulation/assets/1160875/e5ba4afa-c691-4cbd-96b6-ff2c84743ec5)
