### ISSUE TITLE
How to make the plugin panel display in English?

### ISSUE THREAD

**Issue by qq253498229** [krasa/StringManipulation#205]
After a certain update, my plugin panel was displayed in Chinese, which made it difficult for me to understand what each item specifically referred to. 

Where can I set it to force the panel to display in English?

<img width="637" alt="image" src="https://github.com/krasa/StringManipulation/assets/31200516/ddb853d4-0360-4737-9191-d9a5666b2d0f">

如何让插件面板显示成英文？
在某一次更新后，我的插件面板显示成中文，这让我很难理解具体每一项指的是什么。
在哪个地方可以设置，让面板强制显示英语？

**Comment by krasa** [comment]
Install this one https://plugins.jetbrains.com/plugin/2162-string-manipulation/versions/stable/305656
