### ISSUE TITLE
camel case convert to snake case 

### ISSUE THREAD

**Issue by Park-jihoon** [krasa/StringManipulation#207]
When I case convert a word that contains 1 capitalized letter, such as ordTSeq, I get an unwanted result.

Expected value: ord_t_seq 

Resulting value: ord_tseq

Could this be a fix?

**Comment by krasa** [comment]
You can try it 
![image](https://github.com/krasa/StringManipulation/assets/1160875/b98a4145-4575-4bf2-b2e0-efdeefa979ba)

**Comment by Park-jihoon** [comment]
Why don't I see the Between upper letters option in my String manipulation?

The Case switching option only has the

Before numbers and After numbers checkboxes.

- OS : macOS Ventura 13.4 
- IDE : intellij 2023.1.2 Ultimate Edition 
- plugin version : 9.7.1

**Comment by Park-jihoon** [comment]
OK. I've come across the news related to 9.8.0, I'll be waiting with pleasure, thank you.

**Comment by krasa** [comment]
It was released https://plugins.jetbrains.com/plugin/2162-string-manipulation/versions/stable/347234
