### ISSUE TITLE
Multi Replace ignores Find / Find & Replace toolbar.

### ISSUE THREAD

**Issue by m-sharp-ct** [krasa/StringManipulation#217]
**Describe the bug**
Multi Replace does not work whilst using the built-in Regex filter using the find function.
_If this is not meant to then I will raise it as a feature request._

**To Reproduce**
1. Go to a window with a body of text in. In this example I will use a JSON object. 
Example:
```json
      {
        "Name": "Foo",
        "Bar": true,
        "FooBar": "FooBar"
      }
```
3. Click on 'Edit' -> 'Find' -> 'Find...' (Or command/ctrl + F).
4. Select the Regex option in the Find toolbar
5. Enter the Regex pattern you want to match in your body of text.
Example:
`.+?(?=:)`
6. Right-click within the editor window
7. Click String Manipulation
8. Select 'To camelCase' within 'Switch Case...'

**Expected behavior**
I would expect that all highlighted text would match the selected case that you wish to switch to, like it would replace if manually using the Find & Replace function.

**Screenshots**
![image](https://github.com/krasa/StringManipulation/assets/93588005/dc277fc0-7a87-4cb4-b2bb-ca36df3aef22)

Doesn't change anything:
![image](https://github.com/krasa/StringManipulation/assets/93588005/720347eb-214d-44fd-a289-201584d3c390)

Would expect it to change the casing to:
![image](https://github.com/krasa/StringManipulation/assets/93588005/2dbfa132-35dd-47ec-8d47-96cf70a4aa05)

**Environment :**
JetBrains Rider 2023.2.2
Build #RD-232.9921.83, built on September 24, 2023
Licensed to Matt Sharp
Subscription is active until May 31, 2024.
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6
.NET Core v7.0.7 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 8
Metal Rendering is ON
Registry:
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    vcs.empty.toolwindow.show=false
    ide.new.project.model.index.case.sensitivity=true
    database.show.search.tab=false

Non-Bundled Plugins:
    com.settler.rider.specflow (1.17.0)
    wallaby.js (1.0.278)
    com.intellij.ideolog (222.1.0.0)
    com.markskelton.one-dark-theme (5.9.0)
    fr.socolin.application-insights-debug-log-viewer (1.9.0)
    String Manipulation (9.11.3)
    net.cakebuild.cakerider (7.1.0)
    Abc.MoqComplete.Rider (2023.2.0.1)
    com.intellij.resharper.StructuredLogging (2023.2.0.305)
    com.albertoventurini.jetbrains.graphdbplugin (0.7.0)
    ru.adelf.idea.dotenv (2023.2)
    me.seclerp.rider.plugins.efcore (232.1.0)
    com.intellij.bigdatatools.core (232.9921.47)
    com.intellij.bigdatatools.binary.files (232.8660.206)
    com.intellij.bigdatatools.rfs (232.9921.47)
    com.mallowigi.colorHighlighter (17.1.0)
    com.mallowigi (93.1.0)
    mobi.hsz.idea.gitignore (4.5.2)
    app.teamhub (16.1.2)
    com.intellij.resharper.azure (3.50.0.1679-2023.2)

**Comment by krasa** [comment]
Did you select the result?
![image](https://github.com/krasa/StringManipulation/assets/1160875/68e97860-964a-4ee1-8070-21d29495eb79)

**Comment by m-sharp-ct** [comment]
> Did you select the result? ![image](https://user-images.githubusercontent.com/1160875/277972200-68e97860-964a-4ee1-8070-21d29495eb79.png)

Problem solved. Apologies! I didn't know that this was a feature in Rider.
