### ISSUE TITLE
Ignore leading spaces when sorting

### ISSUE THREAD

**Issue by tomasfejfar** [krasa/StringManipulation#22]
I try to sort this code with selection as shown below
 ```php
		>	$bundles[] = new DebugBundle();
			$bundles[] = new SensioDistributionBundle();
			$bundles[] = new WebProfilerBundle();<
```
*(selection shown as >selected text<)*

**Expected:**
 ```php
			$bundles[] = new WebProfilerBundle();
			$bundles[] = new SensioDistributionBundle();
			$bundles[] = new DebugBundle();
```
* Leading whitespace is ignored

**Actual:**
 ```php
			$bundles[] = new DebugBundle(); <------ PROBLEM
			$bundles[] = new WebProfilerBundle();
			$bundles[] = new SensioDistributionBundle();
```
* Leading whitespace is taken into account.

**Comment by krasa** [comment]
even if it was ignored, the result would be 
```
   			$bundles[] = new WebProfilerBundle();
   		$bundles[] = new SensioDistributionBundle();
	$bundles[] = new DebugBundle();
```

**Comment by krasa** [comment]
how about using multicaret with empty selection:
![image](https://cloud.githubusercontent.com/assets/1160875/21725368/6c2c6ac6-d438-11e6-8e6b-1f8fc775ea41.png)

I would just need to implement selection of the whole line when nothing is selected - which should have been there from the beginning anyway.... right now only `Sort by subselection` does that.

**Comment by tomasfejfar** [comment]
That would solve it for me, although it's not very intuitive for anyone not knowing about it. I actually am quite sure that expanding to the whole line should be default for everything. I failed to come up with any actual use-case for the "Actual" case above where it would make sense. Do you have one?

**Comment by krasa** [comment]
imho if you select something, you would expect the operation to be done on the exact selection - or if you select nothing, it will select lines with carets - just like ctrl+c does. 

But you are right that ignoring whitespaces (so that you get the right order) + preserving spaces (so that it does not break formatting) would be nice + preserving trailing commas (as someone else wants)  should cover everything.... Even this:
![image](https://cloud.githubusercontent.com/assets/1160875/21745732/1808fe1e-d532-11e6-8410-979307252450.png)

**Comment by tomasfejfar** [comment]
This seems like a meaningful use to partial-line selection, that should not expand, you are right. 

> ignoring whitespaces (so that you get the right order) + preserving spaces (so that it does not break formatting) would be nice + preserving trailing commas (as someone else wants) should cover everything

Exactly. You actually explained my thoughts better than I did, thanks.

**Comment by krasa** [comment]
You can try it https://github.com/krasa/StringManipulation/releases/download/5.3.143.000.0/StringManipulation.jar

**Comment by krasa** [comment]
Done and released.

**Comment by tomasfejfar** [comment]
I forgot to thank you :) I'm using it regularly and it works great.
