### ISSUE TITLE
"Align to column by ," doesn't align correctly

### ISSUE THREAD

**Issue by m-titov** [krasa/StringManipulation#24]
Example:

Before:

> INSERT INTO address
>(id              , address1                           , address2                      ) VALUES
>(@club_address+1 ,'56 passage de la Coupole'          , '92400 La Défense 6 Courbevoie')         ,
>(@club_address+2 ,'9 Esplanade du Général de Gaulle', '92800 Puteaux'                 )         ;

after: apply this function to all lines except first:

>INSERT INTO address
>(id                 , address1                           , address2                      ) VALUES
>(@club_address+1    , '56 passage de la Coupole'         , '92400 La Défense 6 Courbevoie')            ,
>(@club_address+2    , '9 Esplanade du Général de Gaulle' , '92800 Puteaux'                 )         ;

Please fix.

**Comment by krasa** [comment]
works fine for me:
```
INSERT INTO address
(id              , address1                           , address2 ) VALUES
(@club_address+1 , '56 passage de la Coupole'         , '92400 La Défense 6 Courbevoie') ,
(@club_address+2 , '9 Esplanade du Général de Gaulle' , '92800 Puteaux' ) ;
```

**Comment by m-titov** [comment]
hm.. It doesn't work as expected when file has sql extension...

**Comment by krasa** [comment]
maybe something in tab/space code style config?  I aligned many sql files by it....

**Comment by m-titov** [comment]
Maybe because of this https://youtrack.jetbrains.com/issue/DBE-4050

**Comment by m-titov** [comment]
Can't reproduce anymore
