### ISSUE TITLE
Feature Request: Quote Selection

### ISSUE THREAD

**Issue by dccampbell** [krasa/StringManipulation#25]
Option to wrap the currently selected text in quotes (or possibly other characters). 

Possibly implemented as a `Wrap/Quote...` submenu with entries like:
- Wrap selection in "double quotes"
- Wrap selection in 'single quotes'
- Wrap selection in \`backticks\`

**Comment by krasa** [comment]
Selection is wrapped in quotes by IntelliJ itself, when you press the quote key.

**Comment by dccampbell** [comment]
Not necessarily, auto-wrapping quotes is a configurable setting. Some users have a distaste for that type of autocomplete, or desire it for quotes but not for braces (which isn't a separate option). A key-mappable wrap command would be extremely useful to users who prefer to be more explicit.

**Comment by kjwenger** [comment]
Would like to bump that request as it is useful to be able to toggle 'single quotes' and `back ticks` when a ${variable} needs to be embedded.
