### ISSUE TITLE
Feature Request: toUpperCase + toLowerCase

### ISSUE THREAD

**Issue by JamesMcGuigan** [krasa/StringManipulation#28]
Thank you for your plugin. This is feature request.

You have many options for many advanced case manipulations and variable styles.

However you seem to be missing two of the most basic:
- String.toUpperCase()
- String.toLowerCase()

These are occasionly useful for standard text editing purposes and converting strings to match database schema requirements.

Thank you.

**Comment by krasa** [comment]
IntelliJ already has those.
