### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [krasa/StringManipulation#29]
After installing, I don't see any key bindings to it. I searched in "Keymap" settings for "case" and "string", but nothing appeared.
I just want an easy way to switch between various string cases (camel case etc...).

I use Android Studio 2.3.1.

**Comment by krasa** [comment]
is the plugin enabled?
![image](https://cloud.githubusercontent.com/assets/1160875/25331843/c1ca7e2c-28e4-11e7-8a00-c52225d84cbd.png)

**Comment by AndroidDeveloperLB** [comment]
yes

**Comment by krasa** [comment]
Works for me, try to reinstall it.

**Comment by AndroidDeveloperLB** [comment]
Can you please explain how to use it, and write it on main page of this repo?

**Comment by krasa** [comment]
> Actions are available under Editor context menu, Edit menu, or via the shortcut "alt M" and "alt shift M". You can setup your own shortcuts for better usability.


![image](https://cloud.githubusercontent.com/assets/1160875/25334382/bbb91714-28ee-11e7-8f5f-8fd6c023f148.png)

**Comment by AndroidDeveloperLB** [comment]
A restart did it, but how can I choose for the toggle, which types to toggle between?
Also, is there one that guesses, based on context, which type to use? For example, if it sees it's a static-final variable (constant), it could guess I want to use uppercase only (with underscore character) .

**Comment by krasa** [comment]
Ok then.

What you see is what there is, nothing more, nothing special.

**Comment by AndroidDeveloperLB** [comment]
Can you please add this feature though? Some of the styles there I will never use...

**Comment by krasa** [comment]
Sure, I can click on the "Merge pull request" button.

**Comment by AndroidDeveloperLB** [comment]
If you mean I can add this, sadly I don't know anything about creating Android Studio plugins, so I don't want to ruin yours.
