### ISSUE TITLE
Bad conversion to camelCase

### ISSUE THREAD

**Issue by BorzdeG** [krasa/StringManipulation#3]
. | .
------------ | -------------
origin | testFLEXIBLE_QUERY
expected | test**F**lexibleQuery
actual | test**f**lexibleQuery

. | .
------------ | -------------
origin | testFlexibleQuery_PRODUCTS_FOR_WORKFLOW_ATTACHMENT
expected | test**F**lexible**Q**ueryProductsForWorkflowAttachment
actual | test**f**lexible**q**ueryProductsForWorkflowAttachment

**Comment by krasa** [comment]
expected and actual seems pretty equal to me :)

**Comment by BorzdeG** [comment]
@krasa updated Issue. And yes, they are different - at the beginning of a string of characters different registers

**Comment by krasa** [comment]
I could fix that, but then this would stop to work:

. | .
------------ | -------------
origin | WhOAh_a_TeSt
expected | whoahATest
actual | whOAhATeSt

**Comment by krasa** [comment]
fixed. your example seems more reasonable.

**Comment by BorzdeG** [comment]
thx
