### ISSUE TITLE
Conversion to snake case should convert only case, not other characters

### ISSUE THREAD

**Issue by tomasfejfar** [krasa/StringManipulation#30]
Let's have a string 

`\My\AppBundle\App\Twig\GoogleTagManagerDataLayer`

I want to convert it to

`my.app_bundle.app.twig.google_tag_manager_data_layer`

That seems to be the exact case for string manipulation plugin. But it's currently not possible. If I call "to snake_case" on it, it creates

`my_app_bundle_app_twig_google_tag_manager_data_layer`

I would expect the plugin to work on case (i.e. only convert `[a-z][A-Z]` to `\1_\2`) and not touch *unknown* characters. Current behaviour IMO severely limits use cases. What is this behvaiour's use-case? 

My other typical use case would be 

`Some\PHP\SubNamespace` -> `some/php/sub-namespace.twig` (i.e. replace slashes + to hyphen-case)

**Comment by krasa** [comment]
No use-case, only edge case.

**Comment by tomasfejfar** [comment]
Sorry, I'm not sure I understand.

**Comment by krasa** [comment]
You asked "What is this behvaiour's use-case? " :)

**Comment by tomasfejfar** [comment]
Wow, thank you for speedy fix! ❤

**Comment by tomasfejfar** [comment]
I've just updated to the new version and it works great! Thank you 👍
