### ISSUE TITLE
"Lowercase Fully"... please!

### ISSUE THREAD

**Issue by jonlabelle** [krasa/StringManipulation#33]
Can you introduce a stand-alone lowercase action? It almost seems odd that there's a "Capitalize Fully" command, yet no "Lowercase Fully" action.

I understand there's already a Toggle option, but I would like the ability to bind to one action, to one Keymap.

Other than that... love the plug-in!

**Comment by krasa** [comment]
Edit | Toggle Case
also: https://github.com/krasa/StringManipulation/issues/18 https://github.com/krasa/StringManipulation/issues/16

**Comment by jonlabelle** [comment]
@krasa I understand there is "Toggle" case feature. But that's not what I'm looking for.

*I understand there's already a Toggle option, but I would like the ability to bind to one action, to one Keymap.*

**Comment by krasa** [comment]
So that we understand each other, there is a bundled Toggle Case, and Toggle Case from this plugin.

What would be the advantage over the bundled one? Are you pressing it twice by accident and do not want to press it again?

**Comment by jonlabelle** [comment]
I don't know how else to explain this. I just need a **lowercase** action that is separate and distinct from the toggle case action.

**Comment by krasa** [comment]
I understand it, I just don't understand why. It is one click either way.

**Comment by jonlabelle** [comment]
Well... w/ that logic... please explain to me why you have the "Uppercase" and "Uppercase Fully" actions as a separate and distinct? Since one of them is already handled by the "Togglecase" action, and *one click away*.

**Comment by bbottema** [comment]
I get this was closed in 2017 by people who apparently have trouble expressing themselves, but I'm interested to understand the rationale nonetheless. Frankly after installing the plugin I had trouble understanding the semantic differences between the 'toggle' and the 'to X' approach (and documentation on this is minimal).

From this limited discussion I understand one toggles (duh) and the other is a way one single action? So what's the purpose of the toggle at all if you have distinct actions to go to any other type? Only that you need a single shortcut vs two separate ones? And if that's the case, then why debate the merit of OP's request to have a 'to lowecase' version?

**Comment by krasa** [comment]
#44
What's the purpose of this question?

**Comment by bbottema** [comment]
Haha, ok. No I was just interested in understanding your preference for the toggle scheme in general. I mean you clearly went for a specific approach here with all the toggles, I just don't understand why and maybe I can improve my skills if I do. I'm not criticising you at all, I mean I love the plugin and I love you for making it :)

Or perhaps it just started out like this without too much thought, it got popular and you just decided not to fool around with this setup too much. I've been there a few times myself!

**Comment by krasa** [comment]
For me, it is easier to remember one shortcut, and press it more times, than to have many shortcuts. Also finding a good and free combination of keys is not easy. 
Other people like the opposite + macros, so there are 2 ways. 

I do not have any metrics, so it is just the way it is, nothing deep. :-)
