### ISSUE TITLE
Add opposite of Capitalize selected text which is lowercase

### ISSUE THREAD

**Issue by vanniktech** [krasa/StringManipulation#34]
Given I've got the following text selected `TEST` I'd like to transform it to `test`.

**Comment by krasa** [comment]
Edit | Toggle Case

**Comment by vanniktech** [comment]
That does not quite work when selecting strings that are lower and upper case. Transforming `lsPlu` will yield `ls-plu`.

**Comment by krasa** [comment]
This one -> https://www.jetbrains.com/help/idea/toggling-case.html

**Comment by vanniktech** [comment]
Alright this does seem to be doing the job. Thanks :)
