### ISSUE TITLE
Feature Request:  add "To Words" option

### ISSUE THREAD

**Issue by jaufgang** [krasa/StringManipulation#38]
Right now there is an option `To camelCase (or to words)` but there is no `To words` option.    Sometimes you just want to convert to words but not from camelCase, so you need to do it in 2 steps.  Would be nice to simply have a `To Words` menu item.

**Comment by krasa** [comment]
Maybe a submenu with all the styles would be fine + an action with a popup

**Comment by barseghyanartur** [comment]
Yep, for me - that's the most wanted option - to be able to convert from all cases to just words (and vise-versa).

**Comment by krasa** [comment]
I will just switch the order of the existing action `To camelCase (Or To Words)` so that it does primarily `To Words`, That should be fine, right?
