### ISSUE TITLE
Convert quoted string

### ISSUE THREAD

**Issue by jklap** [krasa/StringManipulation#4]
This would convert a quoted string from current quote (single or double) to the other including any escaping if needed.

For instance, if you have a string such as:
"she's a great car"

It would convert to:
'she\'s a great car'

It should automatically determine whether the string is currently surrounded with single or double quotes and pick the other.

If possible, it should expand from the current selection point (assuming no text is selected) to select the quoted string the cursor is located in.

**Comment by krasa** [comment]
Which language needs this kind of escaping?

**Comment by jklap** [comment]
Groovy

**Comment by matsinet** [comment]
This could be used in PHP as well

**Comment by stribizhev** [comment]
Another great addition could be a quote swapping feature:
  "text 'here'" -> 'text "here"'
  'text "here"' -> "text 'here'"

**Comment by krasa** [comment]
Already in https://github.com/kstenschke/shifter-plugin
