### ISSUE TITLE
[Bug] Sort lines by subselection

### ISSUE THREAD

**Issue by funivan** [krasa/StringManipulation#40]
`Sort lines by subselection` doesn't work
```php
$a = [
  'name'=>2,
  'v2'=>3,
  'va'=>1,
];
```
Here it the code. I selected `2`, `3`, `1` in multiple selection mode -> invoked `Sort lines by subselection` and this just breaks my code. 
Result:
```php
$a = [
  'name'=>2,
  'v2'=>3,
  'v2'=>3,
];
```

P.S. Thanks for the great plugin ;)

**Comment by krasa** [comment]
Works fine for me. Could you make a video?

**Comment by krasa** [comment]
ok, i reproduced it now.

**Comment by funivan** [comment]
@krasa strange. Very strange. I can not reproduce it.
How do you reproduce it ? ))

Another issue. 
P.S. You point letter S in `Case *S*ensitive` and `*S*huffle` options. `Alt+S` combination works for the last one. 
![08 56 37](https://user-images.githubusercontent.com/425208/30577722-c8bdc600-9d18-11e7-8b2b-f8a4db55d476.png)

**Comment by krasa** [comment]
It is broken when there are foldings somewhere before the selection, a bug in IntelliJ imho. I will work around it.

**Comment by krasa** [comment]
Fixed, you can update.
