### ISSUE TITLE
Align by columns: Seperator Delimeter Templates

### ISSUE THREAD

**Issue by utrucceh** [krasa/StringManipulation#47]
Lots of time developers need to same template for separate to code block for different languages, if there is saveTemplate{also removeTemplate && loadTemplate buttons ( t1Btn, t2Btn, ... --> click for load) } action on seperators dialog it become very usefull

**Comment by krasa** [comment]
I hope a history list will be enough
![image](https://user-images.githubusercontent.com/1160875/44370867-70618600-a4dc-11e8-9b9b-fbe58a56c1c1.png)
