### ISSUE TITLE
Bug: Pressing key combo to open popup tries to search instead on IntelliJ IDEA 2018.1

### ISSUE THREAD

**Issue by msheakoski** [krasa/StringManipulation#49]
Pressing alt-M or alt-shift-M causes a search to open within String Manipulation instead of the usual menu. This didn't start happening until IntelliJ IDEA 2018.1. Pressing esc or backspace clears the search and then the intended menu appears.

![screen shot 2018-03-28 at 8 49 12 pm](https://user-images.githubusercontent.com/4156/38064302-4a20e162-32cb-11e8-9a34-4616ead0a3ba.png)

**Comment by krasa** [comment]
Works fine for me.

**Comment by msheakoski** [comment]
I also tried changing the keymap to something like shift-M to test. It seems to forward whatever letter/number you press to String Manipulation's search feature. In this case, it opened the popup and tried searching for "M".

**Comment by msheakoski** [comment]
Still experiencing this issue on 5.8.143.000.0. I completely erased the IDEA preferences dir, created a new empty project, opened up a plain text scratch file, assigned the String Manipulation shortcut to "x". When I press the "x" key, the String Manipulation popup appears in search mode with the letter "x" filled in. I need to press backspace or esc to see the actual menu. Here is more information about the IDEA and JVM which might be helpful:

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

**Comment by krasa** [comment]
"x" shortcut does that for me too, that is IntelliJ issue. But try ctrl+alt+shift+x

**Comment by myoss** [comment]
Plugin Version: 5.8.143.000.0 has this problem
IntelliJ IDEA 2018.1.1 (Ultimate Edition)
Build #IU-181.4445.78, built on April 10, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

Pressing option-M or option-shift-M

<img width="455" alt="jerry_2018-04-14_09-09-26" src="https://user-images.githubusercontent.com/6986459/38762865-8ee2702c-3fc3-11e8-8f64-8e179a825370.png">

**Comment by krasa** [comment]
Try to bind option-M or option-shift-M to for example `Main menu | Code | Generate...`, and if it does the same thing, then report it to JetBrains.

**Comment by myoss** [comment]
@krasa it does the same thing... JetBrains Bug
<img width="359" alt="jerry_2018-04-14_10-38-55" src="https://user-images.githubusercontent.com/6986459/38763520-32b614fe-3fd0-11e8-9c3d-e75a7f74c35e.png">

use the menu, it's ok

![d55cc9e8-1e91-48ea-a0bb-518a3a7e06c7](https://user-images.githubusercontent.com/6986459/38763516-25d46f9c-3fd0-11e8-9e97-ec588cd11b19.png)

**Comment by myoss** [comment]
[https://youtrack.jetbrains.com/issue/IDEA-189066](https://youtrack.jetbrains.com/issue/IDEA-189066)

**Comment by snics** [comment]
+1

**Comment by msheakoski** [comment]
FYI, as of 2018.1.5 I am no longer experiencing this issue.
