### ISSUE TITLE
Bug: using hotkey to switch states doesn't always include all-upper-cases

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [krasa/StringManipulation#50]
I use "switch case" feature in the keys, of this plugin, to switch various cases of selected text:

![image](https://user-images.githubusercontent.com/5357526/38096059-9d6b3bce-337a-11e8-9581-bee56311bc12.png)

It usually works, but I think that only if I use at least 2 words. Suppose you take this example of enum values, that you wish to set all caps (kotlin code) :

    enum class ItemType{
        TermsOfUse , PrivacyPolicy, Acknowledgements,AppVersion
    }

All of them work well, except for "Acknowledgements" which can only be replaced to "acknowledgements" and back to "Acknowledgements".

The others eventually become what they should:  TERMS_OF_USE , PRIVACY_POLICY, APP_VERSION

**Comment by AndroidDeveloperLB** [comment]
Why close ?

**Comment by AndroidDeveloperLB** [comment]
What? When?

**Comment by krasa** [comment]
https://github.com/krasa/StringManipulation/commit/9a98c1aba18b6882a9a7200cff5a4741e4ef1a2b
