### ISSUE TITLE
Request: allow to customize which types of manipulations to use in "switch case"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [krasa/StringManipulation#51]
I use "switch case" feature in the keys, of this plugin, to switch various cases of selected text:

https://user-images.githubusercontent.com/5357526/38096059-9d6b3bce-337a-11e8-9581-bee56311bc12.png

In Kotlin and in Java, there is a specific set of strings rules that we use:

1. helloWorld - variables and functions names
2. HelloWorld - Classes and enums
3. HELLO_WORLD - constant values or enum values
4. hello_world - packages and Android resources.

Other than those, there is no usage that I know of, that the plugin generates.

Please allow to customize which types to use. Maybe even allow it based on the file that is currently edited.

**Comment by AndroidDeveloperLB** [comment]
Why close? Is it now implemented?

**Comment by krasa** [comment]
yes, it will soon be released

**Comment by krasa** [comment]
Install this if you want to try it: 
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/3125214/StringManipulation.zip)

**Comment by AndroidDeveloperLB** [comment]
@krasa Will it also support Kotlin?

**Comment by krasa** [comment]
It is not customizable based on the file type. Maybe ability to define multiple of different actions would be enough?

**Comment by krasa** [comment]
I will try to add it.

**Comment by AndroidDeveloperLB** [comment]
For me I think it will be enough. I write only in Java, XML, and Kotlin.
But maybe people write in more diverse languages, that are a bit different from one another, which require different sets of rules, based on which language you write in.

**Comment by krasa** [comment]
Ok, I will leave it as it is now. It would complicate the UI too much.
It can be always added later if someone asks for it.

**Comment by AndroidDeveloperLB** [comment]
Thank you!

**Comment by AndroidDeveloperLB** [comment]
Can you please add a new enhancement thread for this one, then?
