### ISSUE TITLE
Feature request: Transform PHP Object to Array and back

### ISSUE THREAD

**Issue by gebi84** [krasa/StringManipulation#52]
I tried it in PHPStorm with macros, but that doesn't work:

it would be nice to transform 
`$foo->test = 'ba';`
to
`$foo['test'] = 'bla';`
and backwards.

here my regex:
`\-\>([\w]+)` replace `\[\'$1\'\]`
and
`\[[\"\']([\w]+)[\"\']\]` replace `->$1`

**Comment by funivan** [comment]
I can help you with that. You can create issue here https://github.com/funivan/PhpStorm-Refactoring-Plugin/issues I already have plans to do that ;)

**Comment by krasa** [comment]
That would be great! I personally do not plan to implement language-specific intentions (other than Java).

**Comment by gebi84** [comment]
thx both of you for your answer
