### ISSUE TITLE
Dialog window menu access

### ISSUE THREAD

**Issue by s3r6** [krasa/StringManipulation#56]
While in editor I can access plugin menu via hotkey 
![default](https://user-images.githubusercontent.com/4716175/44467721-a0bc3800-a634-11e8-9e92-e41d099127d9.png)
But in  dialog window I can not call plugin menu, e.g. when renaming android resource.
![default](https://user-images.githubusercontent.com/4716175/44467766-c0ebf700-a634-11e8-93a9-5a5d5c961637.png)

Expected: plugin menu accessible in any dialog windows.

**Comment by krasa** [comment]
Done, but Alt shortcuts conflicts with things, so you have to use alt+shift+M or something...
Although I could make it configurable if you really want to use alt+m.
![image](https://user-images.githubusercontent.com/1160875/44484201-6ca14100-a64d-11e8-92ba-00da90349e1d.png)

**Comment by s3r6** [comment]
Thanks for fast reply. When update will be available?

**Comment by krasa** [comment]
now
