### ISSUE TITLE
Request: add a remove accents entry

### ISSUE THREAD

**Issue by cluelessjoe** [krasa/StringManipulation#59]
It would be nice if strings like éÉö & so forth could be converted to eEo and so forth.

Thanks a lot for your awesome plugin :) 

BTW, i could help in coding this feature (as a Java/Scala coder) but i'm unsure about the correct way to proceed for such a task...

**Comment by krasa** [comment]
There already is `Convert diacritics(accents) to ASCII` action: 
https://github.com/krasa/StringManipulation/blob/master/src/osmedile/intellij/stringmanip/escaping/DiacriticsToAsciiAction.java

**Comment by cluelessjoe** [comment]
I had missed this in "Escape/Encode">"Convert diacritics (accents) to ASCII" 

Thx a lot :)
