### ISSUE TITLE
Do not use the calling context

### ISSUE THREAD

**Issue by BorzdeG** [krasa/StringManipulation#6]
origin code:
```java
public void testMethod() {
	testMethod2(testSub);
}
```

Sets the cursor to "testSub" in line 5 (the word is not highlighted) (<a href="http://habrastorage.org/files/e2f/160/d77/e2f160d7743440cb8d0015af12f94bc3.png">screenshot</a>)
calling the action "To Constant Style"

expect:
```java
public void testMethod() {
	testMethod2(TEST_SUB);
}
```

actual (not only incorrect transformation, but also "broken" code):
```java
public void testMethod() {
TEST_METHOD_(TEST_SUB_;
}
```

**Comment by krasa** [comment]
When nothing is selected, it uses the whole line. 
Imho detecting what should be selected in various situations would be too hard.

**Comment by krasa** [comment]
maybe we could just reuse ctrl+w feature for it, but then why not just click once or twice on ctrl+w and then use the plugin action?

**Comment by BorzdeG** [comment]
Is it possible to somehow attached to Expressions similar to the action of the "Extract Variable"?

**Comment by krasa** [comment]
yeah, I could select any identifier (variable, field, method,...) or string literal (that thing between "...") under a caret in java files.

**Comment by BorzdeG** [comment]
Perhaps we are talking about different things. I'm talking about is: https://habrastorage.org/files/001/229/b81/001229b8161c4f7eb76b1f4d0a981a71.png

**Comment by krasa** [comment]
Oh yeah this, probably doable, but it seems unnecessary, if you are on a identifier or on a string, then it does not make sense to convert anything more than that.

**Comment by krasa** [comment]
I implemented smarter selections for java, properties files, and some generic support. 
You can try it here: https://github.com/krasa/StringManipulation/releases/tag/smarter-selections-prototype

**Comment by krasa** [comment]
it was just released.
