### ISSUE TITLE
How do the "OR" actions work?

### ISSUE THREAD

**Issue by jerry1970** [krasa/StringManipulation#62]
Several actions have a description like "(Or To Words)" (which is the one I would use the most).
How do I get these OR actions to work? I tried shift etc. or calling the action twice but nothing works.

**Comment by CJDennis** [comment]
"To camelCase (Or To Words)" will convert non-camelCased text to camelCase, and camelCased text to words. Using it twice without changing the selection will alternate between which one it does.

**Comment by krasa** [comment]
I hope that's answered. Let me know if you have a better idea how to name those action.

**Comment by jerry1970** [comment]
Ah sorry for the lack of comment. I do understand now. The fact that the selection should not change is key here. Maybe "toggle" is more common? So something like "toggle selected text between camelCale, words"?

**Comment by CJDennis** [comment]
@jerry1970 It's not truly a toggle, because it doesn't have to start as either `camelCase` or `words`. `snake_case` is neither `camelCase` nor `words`, but it will be transformed to `camelCase`.

**Comment by krasa** [comment]
Well, how about removing the boilerplate all together?
![image](https://user-images.githubusercontent.com/1160875/56843254-9b3b7f80-689e-11e9-88f3-ad78b7640d00.png)
