### ISSUE TITLE
Issue turning UPPERCASE WORDS onto Capitalized Words

### ISSUE THREAD

**Issue by Tecktron** [krasa/StringManipulation#64]
Reporting a bug:

If I have text that is all in upper case and then try and change it to capitalize, the text stays unchanged in uppercase. The expected behavior would be that the text changes to capitalized case.

Thanks

**Comment by CJDennis** [comment]
@Tecktron You should give an example. E.g. I believe you mean that `TEXT` should become `Text`, but remains unchanged as `TEXT`.

**Comment by Tecktron** [comment]
To reiterate in case reading what was written was unclear.

Input: `TEXT`
Operation: Capitalize 
Expected output: `Text`
Actual output: `TEXT`

**Comment by krasa** [comment]
@Tecktron any opinion on these cases?
https://github.com/krasa/StringManipulation/blob/c122fbe1221165392f4efa94d695f3bbf6944201/test/osmedile/intellij/stringmanip/styles/WordsCapitalizeActionTest.java#L20-L24

This is how org.apache.commons.lang.WordUtils#capitalizeFully works, not sure if it is fine.
