### ISSUE TITLE
Sort lines / separated list of values

### ISSUE THREAD

**Issue by krasa** [krasa/StringManipulation#7]
```
Case-Sensitive A-z
Case-Sensitive z-A
Case-Insensitive A-Z
Case-Insensitive Z-A
Numerically 0-9
Numerically 9-0
Line Length Short-Long
Line Length Long-Short
With whitespace ignored
```

**Comment by lots0logs** [comment]
:+1:  on this :smile:

**Comment by krasa** [comment]
:+1: perhaps it would be good to do it with a dialog for choosing a separator, as in AlignToColumnsAction.

**Comment by krasa** [comment]
the only missing thing is now `sorting a coma separated list of strings`

**Comment by elapouya** [comment]
I vote to have numerical sorting : that will be very useful to sort a 'find . -ls' or a 'ls -la'
A dialog would appear to choose column and separator (otherwise choose the first numerical column)

**Comment by krasa** [comment]
@elapouya  https://github.com/krasa/StringManipulation/issues/23

**Comment by shanimal** [comment]
I love this plugin btw... 

How about some command aliases?
alt+m+"+s," : split by comma, sort asc and re-join
alt+m+"+case" : uppercase
alt+m+"-case" : lowercase
alt+m+"-case" : lowercase alphanumeric
alt+m+"-casen" : lowercase numeric
alt+m+"-esc" : uescape
alt+m+"+esc" : escape
alt+m+"+snake" : SCREAMING_SNAKE_CASE
alt+m+"-case" : hyphen-case
alt+m+".case" : dot-case
alt+m+"ccase" : camelCase
alt+m+"pcase" : PascalCase
alt+m+"cap" : Capitalize
alt+m+"capf" : Capitalize

**Comment by krasa** [comment]
I don't know what you mean by that

**Comment by shanimal** [comment]
alt+m activates the String Manipulation menu... 
![containers_ _open-channel_jsx_-_dev-portal_-____projects_apps_dev-portal_](https://cloud.githubusercontent.com/assets/283957/25539348/a6d221dc-2bfb-11e7-975d-80b0ec979346.gif)

If you then type "d1" it activates the sort window with the default (or maybe previous(?) sort). 
![sort_settings_and_containers_ _open-channel_jsx_-_dev-portal_-____projects_apps_dev-portal_](https://cloud.githubusercontent.com/assets/283957/25539484/3fec9a0a-2bfc-11e7-9a7e-83544812b096.gif)

So what if you typed "+case" and it would automatically sort uppercase, or "+snake" to automatically SREAMING_SNAKE_CASE the string.

Thanks again for an awesome plugin!

**Comment by krasa** [comment]
created another issue for that, but not sure if it possible

**Comment by shanimal** [comment]
@krasa nevermind.

I don't remember trying it before I posted here. But it looks like it already does a nice search and shows all menu items that contain whatever you type.

So if you type `alt+m` then `+snake` you get this... 

![explore____projects_apps_smart-city-mobile_explore__-_____app_screens_transportationsearch_js__explore_](https://user-images.githubusercontent.com/283957/41261653-900dff1a-6d91-11e8-8b86-ee287de17f5a.png)

**Comment by krasa** [comment]
@shanimal that only works for letters after K,  but if you type `.` dot then it will work for everything. cool.
![image](https://user-images.githubusercontent.com/1160875/41262665-67d21ab2-6de2-11e8-8398-da9b2d617b5c.png)
