### ISSUE TITLE
should not merge PascalCase / camelCase into one menu item

### ISSUE THREAD

**Issue by bluelovers** [krasa/StringManipulation#73]
should not merge PascalCase / camelCase into one menu item

if i wanna camelCase some thing

i have click x 2 for make it is camelCase

hope can like old version, it is split action

**Comment by krasa** [comment]
Maybe configuring your own action would be enough?
![image](https://user-images.githubusercontent.com/1160875/57949912-fe409500-78e5-11e9-8421-f8842ec38a94.png)

**Comment by bluelovers** [comment]
it is work, but i don't think this is good way for make it
