### ISSUE TITLE
Documentation request: how to swap characters

### ISSUE THREAD

**Issue by GROwen** [krasa/StringManipulation#77]
I'd like to swap all characters in a string with a character. i.e.

`string` -> `------`

I thought this may be possible with the `Swap/Characters/Selections...` option but the dialogue doesn't make sense to me, which makes me think I'm misunderstanding what the function of that option is.

 Is this possible with the String Manipulation plugin?

**Comment by krasa** [comment]
it is swapping the order, not replacing all by anmother character

**Comment by krasa** [comment]
you could just use Replace... if that's what you mean
![image](https://user-images.githubusercontent.com/1160875/59076311-b5bd3b80-88d5-11e9-80d5-034276042b12.png)
->
![image](https://user-images.githubusercontent.com/1160875/59076334-c7064800-88d5-11e9-8143-6a8c2a4523ce.png)

**Comment by GROwen** [comment]
👍 that's exactly what I was after, thanks @krasa
