### ISSUE TITLE
Snake case drops numbers

### ISSUE THREAD

**Issue by magnhaug** [krasa/StringManipulation#8]
The symbol `v2Counter` converted to snake_case turns into `v_counter`.
The same holds true for SCREAMING_SNAKE_CASE.
Tested on 4.0.135.445. I imagine this would be a quick fix?

**Comment by krasa** [comment]
yes, it should be easy.

but not sure if it should put an underscore before the number or not...

```
v2Counter -> v2_counter
fooBar2 -> foo_bar2
```

or

```
v2Counter -> v_2_counter
fooBar2 -> foo_bar_2
```

2015-07-14 12:47 GMT+02:00 Magnus Haug <notifications@github.com>:

**Comment by magnhaug** [comment]
I think it all depends, and it's impossible to satisfy all use cases.
I.e. the test method names:
`should_successfully_authenticate_on_v2_api`
versus:
`convert_1_foot_to_12_inches`

But I'd be happy to see the bug fixed, no matter which solution you choose.
If I'm unhappy with an extra or missing underscore after a conversion, I'll just fix that manually later.
