### ISSUE TITLE
Increment/Decrement numbers by 0.1  

### ISSUE THREAD

**Issue by Roman52** [krasa/StringManipulation#82]
Hello! 
Thank you for your plugin, it is really great.
Is it possible to add Increment/Decrement numbers by 0.1 and shortcut for it?
Like emmet https://docs.emmet.io/actions/inc-dec-number/

**Comment by krasa** [comment]
No, but this might https://github.com/kstenschke/shifter-plugin

#17

**Comment by Roman52** [comment]
Hi, @krasa ! Thank you for your answer, but unfortunately shifter-plugin can't do it too.
The minimal step in settings is 2. I can't set 0.1 in settings.
![{379707AE-4C8F-4986-84C8-CBE3827135CF} png](https://user-images.githubusercontent.com/15868406/60883231-50e95e00-a252-11e9-8a51-a78a7ba13c2e.jpg)

Anyway, thank you for your answer and recommendation.
