### ISSUE TITLE
Missing Order for Example

### ISSUE THREAD

**Issue by beam2web** [krasa/StringManipulation#87]
I want to order the strings in a file like this example:
test_a=n1
test_a=n300
test_a.1=n10000
test_a.1=n60
test_b=n2000
test_b=n2000
test_b.2=n10600
test_b.2=n10600
test_c=n4
test_c=n6328
test_c.3=n2000
test_c.3=n6
test_d=n10000
test_d=n7
test_d.4=n
test_d.4=n300
test_e=n10600
test_e=n70
test_e=n880
test_e.5=n2328
test_e.5=n4328
test_e.5=n6328

But i don't get the same result: (Case Sensitive, Ascending, Collator)
test_a.1=n10000
test_a.1=n60
test_a=n1
test_a=n300
test_b.2=n10600
test_b.2=n10600
test_b=n2000
test_b=n2000
test_c.3=n2000
test_c.3=n6
test_c=n4
test_c=n6328
test_d.4=n
test_d.4=n300
test_d=n10000
test_d=n7
test_e.5=n2328
test_e.5=n4328
test_e.5=n6328
test_e=n10600
test_e=n70
test_e=n880

Have you got an idea to do that automatically?

**Comment by krasa** [comment]
You would need to implement your own comparator, then make a plugin or use https://github.com/dkandalov/live-plugin/
