### ISSUE TITLE
Insert new random UUID

### ISSUE THREAD

**Issue by DanielWeigl** [krasa/StringManipulation#88]
**Is your feature request related to a problem? Please describe.**
Often i need a uuid (eg. for unit tests or for the ID of a new entity in databases) - would be nice to have a "Insert new UUID" action.

**Describe the solution you'd like**
Insert the result of `UUID.randomUUID().toString()` at the current cursor location

**Describe alternatives you've considered**
Currently i switch to a terminal, run `uuidgen`, copy result, switch back to intellij and insert

**Additional context**
Maybe a configuration to select which UUID generation to use, https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random) - but imo the java default v4 is mostly used

**Comment by krasa** [comment]
How about this? https://plugins.jetbrains.com/plugin/8320-uuid-generator

**Comment by DanielWeigl** [comment]
Good point - will have a look on it, thx
