### ISSUE TITLE
How to change `HelloWorld` to `helloWorld`?

### ISSUE THREAD

**Issue by freewind** [krasa/StringManipulation#9]
`HelloWorld`  -> `helloWorld`, how to convert it with this plugin just in one time?

I have to press do it with 2 steps:

1. `option + m` + `5`, to convert it to `HELLO_WORLD`
2. `option + m` + `5`, to convert it to `helloWorld`

Do I miss anything that I can do it just in one step?

**Comment by krasa** [comment]
I will have to add an action for that.

**Comment by krasa** [comment]
done

**Comment by freewind** [comment]
:+1:
