### ISSUE TITLE
Sort Lines - group by level

### ISSUE THREAD

**Issue by 6562680** [krasa/StringManipulation#93]
Possible duplicate of sort by column*

If put the checkbox then press "sort" the plugin still sorting all lines instead of new sorting for each paragraph. There is strange use-case to sort text with blank lines preserved but still ignore the blank lines.

The example:

>lang.ini
```
a:1
b:1
c:1

b:1
c:1
a:1
```

it should be
```
a:1
b:1
c:1

a:1
b:1
c:1
```

instead of

```
a:1
a:1
b:1

b:1
c:1
c:1
```

Same about sorting by column - sometimes we need to sort objects with tab/double space chars at line beginning, so we need then new sorting for each prefix.

I mean:
```
a
  c
  b
b
c
```

should be
```
a
  b
  c
b
c
```
instead of

```
a
b
c
  b
  c
```

**Comment by krasa** [comment]
So what you need is "Sort paragraphs", not "Sort lines". 
Pull request welcomed.

Not sure what is the alghorithm in the second problem. Butt if you need sort by column, then use "sort by subselection" and select only rows in with the specific column.

**Comment by 6562680** [comment]
Next time i would work with 2mb deep associative language file i, of course, will use my mouse to select each 12 lines to sort it with damn Shortcut + MouseClick combination.

I think, i will finish my work in next century then

**Comment by krasa** [comment]
You might easily do it with https://github.com/dkandalov/live-plugin

**Comment by 6562680** [comment]
will try ty

**Comment by krasa** [comment]
Maybe it would be better to sort it like a tree.
Otherwise it won't sort this:
```
c
a
  c
  b
b
```
into:
```
a
  b
  c
b
c
```
